-- SIGDEC v1.71 — catálogo municipal complementar para contexto territorial
INSERT INTO legal_norms(jurisdiction,state_code,municipality,norm_type,norm_number,norm_year,title,summary,status,source_url,official_source,topics,verified_at,verification_notes)
VALUES
('MUNICIPAL','SP','Ubatuba','Lei','2333',2003,'Normas para aprovação de projetos de edificação no loteamento Praia de Itamambuca','Norma urbanística específica de loteamento, relevante à análise de uso, ocupação e edificação.','ACTIVE','https://www.ubatuba.sp.gov.br/administracao-direta/secretaria-municipal-de-urbanismo/estudo-de-viabilidade-tecnica-uso-e-ocupacao-do-solo/','Prefeitura Municipal de Ubatuba · Secretaria de Urbanismo','["urbanismo","uso_solo","edificacao","restricao_loteamento","itamambuca"]'::jsonb,now(),'Referência oficial da SMU. Conferir íntegra e alterações antes da aplicação.'),
('MUNICIPAL','SP','Ubatuba','Lei','2507',2004,'Condições para aprovação de projeto de edificação no loteamento Recanto da Lagoinha','Norma urbanística específica aplicável ao loteamento Recanto da Lagoinha.','ACTIVE','https://www.ubatuba.sp.gov.br/administracao-direta/secretaria-municipal-de-urbanismo/estudo-de-viabilidade-tecnica-uso-e-ocupacao-do-solo/','Prefeitura Municipal de Ubatuba · Secretaria de Urbanismo','["urbanismo","uso_solo","edificacao","restricao_loteamento","lagoinha"]'::jsonb,now(),'Referência oficial da SMU. Conferir íntegra e alterações antes da aplicação.'),
('MUNICIPAL','SP','Ubatuba','Lei','3887',2016,'Regularização de registro, localização e funcionamento de serviços de hospedagem de baixo impacto','Disciplina aspectos municipais de regularização e funcionamento de hospedagem de baixo impacto.','ACTIVE','https://www.ubatuba.sp.gov.br/administracao-direta/secretaria-municipal-de-urbanismo/estudo-de-viabilidade-tecnica-uso-e-ocupacao-do-solo/','Prefeitura Municipal de Ubatuba · Secretaria de Urbanismo','["urbanismo","uso_solo","regularizacao","hospedagem"]'::jsonb,now(),'Referência oficial da SMU. Conferir íntegra e alterações antes da aplicação.'),
('MUNICIPAL','SP','Ubatuba','Lei','3952',2016,'Instalação de Estação Rádio Base - ERB','Disciplina instalação de estação rádio base no Município.','ACTIVE','https://www.ubatuba.sp.gov.br/administracao-direta/secretaria-municipal-de-urbanismo/estudo-de-viabilidade-tecnica-uso-e-ocupacao-do-solo/','Prefeitura Municipal de Ubatuba · Secretaria de Urbanismo','["urbanismo","infraestrutura","telecom","edificacao"]'::jsonb,now(),'Referência oficial da SMU. Conferir íntegra e alterações antes da aplicação.'),
('MUNICIPAL','SP','Ubatuba','Lei','4294',2020,'Regularização de construções','Dispõe sobre regularização de construções e providências correlatas no Município.','ACTIVE','https://www.ubatuba.sp.gov.br/administracao-direta/secretaria-municipal-de-urbanismo/estudo-de-viabilidade-tecnica-uso-e-ocupacao-do-solo/','Prefeitura Municipal de Ubatuba · Secretaria de Urbanismo','["urbanismo","regularizacao","construcao","edificacao","habitacao"]'::jsonb,now(),'Referência oficial da SMU. Conferir íntegra e alterações antes da aplicação.'),
('MUNICIPAL','SP','Ubatuba','Lei','3258',2009,'Criação do Conselho Municipal de Meio Ambiente - CMMA','Institui o Conselho Municipal de Meio Ambiente e integra a governança ambiental municipal.','ACTIVE','https://conselhos.ubatuba.sp.gov.br/cmma/','Prefeitura Municipal de Ubatuba · Portal dos Conselhos','["meio_ambiente","governanca","cmma","licenciamento"]'::jsonb,now(),'Referência oficial do Portal dos Conselhos. Conferir texto consolidado.'),
('MUNICIPAL','SP','Ubatuba','Lei Orgânica','LOM',NULL,'Lei Orgânica do Município de Ubatuba','Norma fundamental municipal, relevante à distribuição de competências, política urbana, ambiental e administrativa.','ACTIVE','https://planodiretor.ubatuba.sp.gov.br/legislacao/page/3/','Prefeitura Municipal de Ubatuba · Plano Diretor','["competencia_municipal","urbanismo","meio_ambiente","administracao","defesa_civil"]'::jsonb,now(),'Referência oficial cadastrada. Conferir íntegra e emendas antes de citação específica.')
ON CONFLICT DO NOTHING;
