"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Summary={activeRisks:number;openAlerts:number;openMonitoringEvents:number;s2idRecords:number;trainings:number;recoveryActions:number;civilDefenseActions:number;openSupportRequests:number;openSidecExports:number};
type Risk={id:string;code:string;title:string;category:string;probability:number;impact:number;status:string;mitigation?:string|null};
type Alert={id:string;severity:"INFO"|"WATCH"|"WARNING"|"EMERGENCY";title:string;message:string;status:string;createdAt:string;monitoringEventId?:string|null;stationCode?:string|null;stationName?:string|null};
type CivilAction={id:string;incidentId?:string|null;protocol?:string|null;actionType:string;title:string;description?:string|null;startedAt:string;participantsCount:number;createdByName:string};
type SupportRequest={id:string;incidentId?:string|null;protocol?:string|null;requestType:string;status:string;destination?:string|null;justification:string;externalProtocol?:string|null;createdAt:string;createdByName:string};
type SidecPending={incidentId:string;protocol:string;summary:string;priority:string;typeCode?:string|null;cobradeCode?:string|null;pendingStatus:string;missing:string[];exportId?:string|null;revision?:number|null;exportStatus?:string|null;externalProtocol?:string|null;artifactSealed:boolean;dueAt?:string|null;severity?:string|null;overdue:boolean;updatedAt:string};
type SidecDeadlinePolicy={pendingStatus:"PACKAGE_READY"|"AWAITING_PROTOCOL"|"AWAITING_RETURN"|"REJECTED";warningAfterHours:number;severity:"WATCH"|"WARNING"|"EMERGENCY";enabled:boolean};
type SidecDeadlineAlert={id:string;incidentId:string;exportId:string;protocol:string;summary:string;revision:number;pendingStatus:string;severity:string;dueAt:string;detectedAt:string;acknowledgedAt?:string|null};
type SidecArchiveHealth={exportId:string;incidentId:string;protocol:string;summary:string;revision:number;archivedAt:string;objectLockMode?:string|null;retainUntil?:string|null;legalHold:boolean;existsRemote?:boolean|null;hashValid?:boolean|null;verifiedAt?:string|null;errorMessage?:string|null;health:"HEALTHY"|"STALE"|"CRITICAL"};
type SidecReplicationHealth={exportId:string;incidentId:string;protocol:string;summary:string;revision:number;primaryRetainUntil?:string|null;primaryLegalHold:boolean;primaryHashValid?:boolean|null;primaryObservedHash?:string|null;primaryVerifiedAt?:string|null;replicaCreated:boolean;replicaRetainUntil?:string|null;replicaLegalHold?:boolean|null;replicaHashValid?:boolean|null;replicaObservedHash?:string|null;replicaVerifiedAt?:string|null;primaryError?:string|null;replicaError?:string|null;health:"HEALTHY"|"MISSING_REPLICA"|"POLICY_DRIFT"|"STALE"|"CRITICAL"};
const sidecPendingLabels:Record<string,string>={NOT_READY:"Incompleto",READY_TO_PACKAGE:"Pronto para gerar pacote",PACKAGE_READY:"Pacote pronto para exportar",AWAITING_PROTOCOL:"Aguardando protocolo externo",AWAITING_RETURN:"Aguardando retorno estadual",REJECTED:"Devolvido / rejeitado"};
export default function GestaoPage(){
 const [data,setData]=useState<Summary|null>(null),[risks,setRisks]=useState<Risk[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[actions,setActions]=useState<CivilAction[]>([]),[supportRequests,setSupportRequests]=useState<SupportRequest[]>([]),[sidecPending,setSidecPending]=useState<SidecPending[]>([]),[sidecPolicies,setSidecPolicies]=useState<SidecDeadlinePolicy[]>([]),[sidecDeadlineAlerts,setSidecDeadlineAlerts]=useState<SidecDeadlineAlert[]>([]),[sidecArchiveHealth,setSidecArchiveHealth]=useState<SidecArchiveHealth[]>([]),[sidecReplicationHealth,setSidecReplicationHealth]=useState<SidecReplicationHealth[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`${API}${path}`,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";return null}if(!r.ok)throw new Error("Não foi possível concluir a operação.");return r.json()},[]);
 const load=useCallback(async()=>{try{const [s,r,a,ca,sr,sp,pol,dal,worm,repl]=await Promise.all([request("/api/v1/management/summary"),request("/api/v1/risks"),request("/api/v1/alerts"),request("/api/v1/civil-defense/actions"),request("/api/v1/support-requests"),request("/api/v1/sidec/pending"),request("/api/v1/sidec/deadline-policies"),request("/api/v1/sidec/deadline-alerts?open=true"),request("/api/v1/sidec/archive-health"),request("/api/v1/sidec/archive-replication-health")]);if(s)setData(s);if(r)setRisks(r.items??[]);if(a)setAlerts(a.items??[]);if(ca)setActions(ca.items??[]);if(sr)setSupportRequests(sr.items??[]);if(sp)setSidecPending(sp.items??[]);if(pol)setSidecPolicies(pol.items??[]);if(dal)setSidecDeadlineAlerts(dal.items??[]);if(worm)setSidecArchiveHealth(worm.items??[]);if(repl)setSidecReplicationHealth(repl.items??[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Serviço indisponível.")}},[request]);
 useEffect(()=>{load()},[load]);
 async function createRisk(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/risks",{method:"POST",body:JSON.stringify({code:String(f.get("code")),title:String(f.get("title")),category:String(f.get("category")),probability:Number(f.get("probability")),impact:Number(f.get("impact")),mitigation:String(f.get("mitigation")||"")||undefined})});form.reset();setMessage("Risco registrado com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar risco.")}finally{setBusy(false)}}
 async function changeStatus(kind:"risks"|"alerts",id:string,status:string){setBusy(true);setMessage("");try{await request(`/api/v1/${kind}/${id}/status`,{method:"PATCH",body:JSON.stringify({status})});setMessage("Situação atualizada com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar situação.")}finally{setBusy(false)}}
 async function changeSupportStatus(id:string,status:string){setBusy(true);setMessage("");try{await request(`/api/v1/support-requests/${id}/status`,{method:"PATCH",body:JSON.stringify({status})});setMessage("Solicitação operacional atualizada.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar solicitação.")}finally{setBusy(false)}}
 async function acknowledgeSidecDeadline(id:string){
  setBusy(true);setMessage("");
  try{await request(`/api/v1/sidec/deadline-alerts/${id}/ack`,{method:"PATCH",body:"{}"});setMessage("Alerta de prazo SIDEC reconhecido.");await load()}
  catch(e){setMessage(e instanceof Error?e.message:"Falha ao reconhecer alerta SIDEC.")}finally{setBusy(false)}
 }
 function updateSidecPolicy(index:number,patch:Partial<SidecDeadlinePolicy>){
  setSidecPolicies(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
 }
 async function saveSidecPolicies(){
  setBusy(true);setMessage("");
  try{await request("/api/v1/sidec/deadline-policies",{method:"PUT",body:JSON.stringify({items:sidecPolicies})});setMessage("SLAs operacionais SIDEC atualizados.");await load()}
  catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar SLAs SIDEC.")}finally{setBusy(false)}
 }
 async function verifySidecArchive(exportId:string){
  setBusy(true);setMessage("");
  try{const result=await request(`/api/v1/sidec-exports/${exportId}/archive/verify`,{method:"POST",body:"{}"});setMessage(result?.hashValid?"Arquivo WORM íntegro: SHA-256 remoto confirmado.":"Verificação WORM detectou problema.");await load()}
  catch(e){setMessage(e instanceof Error?e.message:"Falha ao verificar arquivo WORM.")}finally{setBusy(false)}
 }
 async function createAlert(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/alerts",{method:"POST",body:JSON.stringify({riskId:String(f.get("riskId")||"")||undefined,severity:String(f.get("severity")),title:String(f.get("title")),message:String(f.get("message"))})});form.reset();setMessage("Alerta registrado com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar alerta.")}finally{setBusy(false)}}
 const cards=data?[["Riscos ativos",data.activeRisks],["Alertas abertos",data.openAlerts],["Eventos de monitoramento",data.openMonitoringEvents],["Ações da Defesa Civil",data.civilDefenseActions],["Solicitações em aberto",data.openSupportRequests],["Pendências SIDEC",sidecPending.length],["Alertas SLA SIDEC",sidecDeadlineAlerts.length],["WORM críticos",sidecArchiveHealth.filter(x=>x.health==="CRITICAL").length],["WORM vencidos",sidecArchiveHealth.filter(x=>x.health==="STALE").length],["Réplicas ausentes",sidecReplicationHealth.filter(x=>x.health==="MISSING_REPLICA").length],["Drift WORM",sidecReplicationHealth.filter(x=>x.health==="POLICY_DRIFT").length],["Registros S2iD",data.s2idRecords],["Treinamentos",data.trainings],["Ações de recuperação",data.recoveryActions]]:[];
 return <main className="shell moduleShell"><header className="listHeader"><div><span className="eyebrow">SIGDEC · DEFESA CIVIL · UBATUBA</span><h1>Centro de Gestão</h1><p>Riscos, alertas e visão consolidada da preparação e resposta municipal.</p></div><Link className="secondaryLink" href="/painel">Painel</Link></header>
 {error&&<p className="errorMessage">{error}</p>}{message&&<p className="formMessage">{message}</p>}
 <section className="dataGrid">{cards.map(([n,v])=><article className="card" key={String(n)}><h2>{n}</h2><p style={{fontSize:"2rem",fontWeight:900}}>{v}</p></article>)}</section>
 <section className="operationsGrid" style={{marginTop:18}}>
  <form className="incidentForm compactForm" onSubmit={createRisk}><h2>Novo risco</h2><label>Código<input name="code" required placeholder="R-001"/></label><label>Título<input name="title" required/></label><label>Categoria<input name="category" required placeholder="Geológico, hidrológico..."/></label><div className="formGrid"><label>Probabilidade<select name="probability" defaultValue="3">{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Impacto<select name="impact" defaultValue="3">{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Mitigação<textarea name="mitigation"/></label><button className="primaryButton" disabled={busy}>Registrar risco</button></form>
  <form className="incidentForm compactForm" onSubmit={createAlert}><h2>Novo alerta</h2><label>Risco relacionado<select name="riskId"><option value="">Sem vínculo</option>{risks.map(x=><option value={x.id} key={x.id}>{x.code} · {x.title}</option>)}</select></label><label>Severidade<select name="severity" defaultValue="WATCH"><option value="INFO">Informativo</option><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label>Título<input name="title" required/></label><label>Mensagem<textarea name="message" required/></label><button className="primaryButton" disabled={busy}>Registrar alerta</button></form>
 </section>
 <section style={{marginTop:18}}><h2>Riscos priorizados</h2><div className="dataGrid">{risks.length===0?<div className="infoCard">Nenhum risco registrado.</div>:risks.map(x=><article className="card" key={x.id}><h2>{x.code} · {x.title}</h2><p><strong>{x.category}</strong> · nível {x.probability*x.impact}/25</p><p>Probabilidade {x.probability} · Impacto {x.impact} · {x.status}</p>{x.mitigation&&<p>{x.mitigation}</p>}<div className="headerActions">{x.status!=="ACTIVE"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("risks",x.id,"ACTIVE")}>Reabrir</button>}{x.status==="ACTIVE"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("risks",x.id,"MITIGATED")}>Marcar mitigado</button>}{x.status!=="CLOSED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("risks",x.id,"CLOSED")}>Encerrar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Alertas recentes</h2><div className="dataGrid">{alerts.length===0?<div className="infoCard">Nenhum alerta registrado.</div>:alerts.slice(0,12).map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.severity}</strong> · {x.status}</p><p>{x.message}</p>{x.monitoringEventId&&<p><strong>Origem:</strong> monitoramento{x.stationCode?` · ${x.stationCode}`:""}{x.stationName?` · ${x.stationName}`:""}</p>}<div className="headerActions">{x.status==="DRAFT"&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>changeStatus("alerts",x.id,"PUBLISHED")}>Publicar</button>}{x.status!=="CLOSED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("alerts",x.id,"CLOSED")}>Encerrar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Ações municipais recentes</h2><div className="dataGrid">{actions.length===0?<div className="infoCard">Nenhuma ação registrada.</div>:actions.slice(0,12).map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.actionType}</strong>{x.protocol?` · ${x.protocol}`:""}</p><p>{new Date(x.startedAt).toLocaleString("pt-BR")} · participantes {x.participantsCount}</p>{x.description&&<p>{x.description}</p>}</article>)}</div></section>
 <section style={{marginTop:18}}><h2>Solicitações operacionais</h2><div className="dataGrid">{supportRequests.length===0?<div className="infoCard">Nenhuma solicitação registrada.</div>:supportRequests.slice(0,20).map(x=><article className="card" key={x.id}><h2>{x.requestType}</h2><p><strong>{x.status}</strong>{x.protocol?` · ${x.protocol}`:""}{x.destination?` · ${x.destination}`:""}</p><p>{x.justification}</p>{x.externalProtocol&&<p>Protocolo externo: {x.externalProtocol}</p>}<div className="headerActions">{x.status==="DRAFT"&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>changeSupportStatus(x.id,"SUBMITTED")}>Protocolar</button>}{x.status==="SUBMITTED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeSupportStatus(x.id,"IN_ANALYSIS")}>Em análise</button>}{x.status==="IN_ANALYSIS"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeSupportStatus(x.id,"APPROVED")}>Aprovar</button>}{["APPROVED","IN_ANALYSIS"].includes(x.status)&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeSupportStatus(x.id,"COMPLETED")}>Concluir</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Redundância WORM</h2><p>Comparação entre o arquivo principal e a réplica secundária, incluindo política e SHA-256 observado.</p><div className="dataGrid">{sidecReplicationHealth.length===0?<div className="infoCard">Nenhum arquivo WORM disponível para análise de redundância.</div>:sidecReplicationHealth.map(x=><article className={x.health==="HEALTHY"?"card":"warningCard"} key={x.exportId}><h2>{x.protocol} · R{x.revision}</h2><p><strong>{x.health==="HEALTHY"?"Redundância saudável":x.health==="MISSING_REPLICA"?"Réplica ausente":x.health==="POLICY_DRIFT"?"Política divergente":x.health==="STALE"?"Verificação vencida":"Falha crítica"}</strong></p><p>{x.summary}</p><p>Primário: {x.primaryHashValid===true?"SHA-256 válido":x.primaryHashValid===false?"hash divergente":"sem confirmação"} · Réplica: {!x.replicaCreated?"ausente":x.replicaHashValid===true?"SHA-256 válido":x.replicaHashValid===false?"hash divergente":"sem confirmação"}</p>{x.primaryObservedHash&&x.replicaObservedHash&&<p><strong>Hashes cruzados:</strong> {x.primaryObservedHash===x.replicaObservedHash?"idênticos":"DIVERGENTES"}</p>}{x.primaryError&&<p>Primário: {x.primaryError}</p>}{x.replicaError&&<p>Réplica: {x.replicaError}</p>}<Link className="secondaryLink" href={`/ocorrencias/${x.incidentId}/sidec`}>Tratar redundância</Link></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Preservação WORM / Object Lock</h2><p>Monitor de disponibilidade, SHA-256 remoto e atualidade da última verificação dos ZIPs arquivados.</p><div className="dataGrid">{sidecArchiveHealth.length===0?<div className="infoCard">Nenhum ZIP SIDEC arquivado em WORM.</div>:sidecArchiveHealth.map(x=><article className={x.health==="CRITICAL"?"warningCard":"card"} key={x.exportId}><h2>{x.protocol} · R{x.revision}</h2><p><strong>{x.health==="HEALTHY"?"Saudável":x.health==="STALE"?"Verificação vencida":"Falha crítica"}</strong>{x.objectLockMode?` · ${x.objectLockMode}`:""}{x.legalHold?" · legal hold":""}</p><p>{x.summary}</p><p>{x.hashValid===true?"SHA-256 remoto confirmado":x.hashValid===false?"SHA-256 remoto divergente":"Sem confirmação recente do hash"}</p>{x.retainUntil&&<p>Retenção até {new Date(x.retainUntil).toLocaleString("pt-BR")}</p>}{x.verifiedAt&&<p>Última verificação: {new Date(x.verifiedAt).toLocaleString("pt-BR")}</p>}{x.errorMessage&&<p>{x.errorMessage}</p>}<div className="headerActions"><Link className="secondaryLink" href={`/ocorrencias/${x.incidentId}/sidec`}>Abrir revisão</Link><button type="button" className="primaryButton" disabled={busy} onClick={()=>void verifySidecArchive(x.exportId)}>Verificar agora</button></div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Alertas de prazo SIDEC</h2><div className="dataGrid">{sidecDeadlineAlerts.length===0?<div className="infoCard">Nenhum SLA SIDEC vencido sem reconhecimento.</div>:sidecDeadlineAlerts.map(x=><article className="card" key={x.id}><h2>{x.protocol} · R{x.revision}</h2><p><strong>{x.severity}</strong> · {sidecPendingLabels[x.pendingStatus]??x.pendingStatus}</p><p>{x.summary}</p><p><strong>Prazo:</strong> {new Date(x.dueAt).toLocaleString("pt-BR")}</p><p>Detectado em {new Date(x.detectedAt).toLocaleString("pt-BR")}</p><div className="headerActions"><Link className="secondaryLink" href={`/ocorrencias/${x.incidentId}/sidec`}>Abrir ocorrência</Link><button type="button" className="primaryButton" disabled={busy} onClick={()=>void acknowledgeSidecDeadline(x.id)}>Reconhecer alerta</button></div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>SLAs operacionais SIDEC</h2><p>Parâmetros administrativos de acompanhamento; não representam prazos legais.</p><div className="dataGrid">{sidecPolicies.map((x,index)=><article className="card" key={x.pendingStatus}><h2>{sidecPendingLabels[x.pendingStatus]??x.pendingStatus}</h2><label>Alertar após (horas)<input type="number" min="1" max="8760" value={x.warningAfterHours} onChange={e=>updateSidecPolicy(index,{warningAfterHours:Number(e.target.value)})}/></label><label>Severidade<select value={x.severity} onChange={e=>updateSidecPolicy(index,{severity:e.target.value as SidecDeadlinePolicy["severity"]})}><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label><input type="checkbox" checked={x.enabled} onChange={e=>updateSidecPolicy(index,{enabled:e.target.checked})}/> Ativo</label></article>)}</div><button type="button" className="primaryButton" disabled={busy||sidecPolicies.length===0} onClick={()=>void saveSidecPolicies()}>Salvar SLAs SIDEC</button></section>
 <section style={{marginTop:18}}><h2>Pendências de interoperabilidade SIDEC/SP</h2><div className="dataGrid">{sidecPending.length===0?<div className="infoCard">Nenhuma pendência SIDEC ativa.</div>:sidecPending.slice(0,40).map(x=><article className="card" key={x.incidentId}><h2>{x.protocol}{x.revision?` · R${x.revision}`:""}</h2><p><strong>{sidecPendingLabels[x.pendingStatus]??x.pendingStatus}</strong>{x.overdue?" · VENCIDO":""} · prioridade {x.priority}{x.cobradeCode?` · COBRADE ${x.cobradeCode}`:""}</p><p>{x.summary}</p>{x.missing?.length>0&&<p><strong>Falta:</strong> {x.missing.join(" · ")}</p>}{x.dueAt&&<p><strong>SLA:</strong> {new Date(x.dueAt).toLocaleString("pt-BR")}{x.severity?` · ${x.severity}`:""}</p>}{x.externalProtocol&&<p>Protocolo externo: {x.externalProtocol}</p>}{x.exportId&&<p>{x.artifactSealed?"ZIP selado e imutável":"ZIP ainda não selado"}</p>}<p>Atualizado em {new Date(x.updatedAt).toLocaleString("pt-BR")}</p><Link className="secondaryLink" href={`/ocorrencias/${x.incidentId}/sidec`}>Tratar pendência</Link></article>)}</div></section>
 </main>
}