"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Summary={activeRisks:number;openAlerts:number;openMonitoringEvents:number;s2idRecords:number;trainings:number;recoveryActions:number};
type Risk={id:string;code:string;title:string;category:string;probability:number;impact:number;status:string;mitigation?:string|null};
type Alert={id:string;severity:"INFO"|"WATCH"|"WARNING"|"EMERGENCY";title:string;message:string;status:string;createdAt:string;monitoringEventId?:string|null;stationCode?:string|null;stationName?:string|null};
export default function GestaoPage(){
 const [data,setData]=useState<Summary|null>(null),[risks,setRisks]=useState<Risk[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`${API}${path}`,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";return null}if(!r.ok)throw new Error("Não foi possível concluir a operação.");return r.json()},[]);
 const load=useCallback(async()=>{try{const [s,r,a]=await Promise.all([request("/api/v1/management/summary"),request("/api/v1/risks"),request("/api/v1/alerts")]);if(s)setData(s);if(r)setRisks(r.items??[]);if(a)setAlerts(a.items??[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Serviço indisponível.")}},[request]);
 useEffect(()=>{load()},[load]);
 async function createRisk(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/risks",{method:"POST",body:JSON.stringify({code:String(f.get("code")),title:String(f.get("title")),category:String(f.get("category")),probability:Number(f.get("probability")),impact:Number(f.get("impact")),mitigation:String(f.get("mitigation")||"")||undefined})});form.reset();setMessage("Risco registrado com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar risco.")}finally{setBusy(false)}}
 async function changeStatus(kind:"risks"|"alerts",id:string,status:string){setBusy(true);setMessage("");try{await request(`/api/v1/${kind}/${id}/status`,{method:"PATCH",body:JSON.stringify({status})});setMessage("Situação atualizada com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar situação.")}finally{setBusy(false)}}
 async function createAlert(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/alerts",{method:"POST",body:JSON.stringify({riskId:String(f.get("riskId")||"")||undefined,severity:String(f.get("severity")),title:String(f.get("title")),message:String(f.get("message"))})});form.reset();setMessage("Alerta registrado com sucesso.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar alerta.")}finally{setBusy(false)}}
 const cards=data?[["Riscos ativos",data.activeRisks],["Alertas abertos",data.openAlerts],["Eventos de monitoramento",data.openMonitoringEvents],["Registros S2iD",data.s2idRecords],["Treinamentos",data.trainings],["Ações de recuperação",data.recoveryActions]]:[];
 return <main className="shell moduleShell"><header className="listHeader"><div><span className="eyebrow">SIGDEC · DEFESA CIVIL · UBATUBA</span><h1>Centro de Gestão</h1><p>Riscos, alertas e visão consolidada da preparação e resposta municipal.</p></div><Link className="secondaryLink" href="/painel">Painel</Link></header>
 {error&&<p className="errorMessage">{error}</p>}{message&&<p className="formMessage">{message}</p>}
 <section className="dataGrid">{cards.map(([n,v])=><article className="card" key={String(n)}><h2>{n}</h2><p style={{fontSize:"2rem",fontWeight:900}}>{v}</p></article>)}</section>
 <section className="operationsGrid" style={{marginTop:18}}>
  <form className="incidentForm compactForm" onSubmit={createRisk}><h2>Novo risco</h2><label>Código<input name="code" required placeholder="R-001"/></label><label>Título<input name="title" required/></label><label>Categoria<input name="category" required placeholder="Geológico, hidrológico..."/></label><div className="formGrid"><label>Probabilidade<select name="probability" defaultValue="3">{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Impacto<select name="impact" defaultValue="3">{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Mitigação<textarea name="mitigation"/></label><button className="primaryButton" disabled={busy}>Registrar risco</button></form>
  <form className="incidentForm compactForm" onSubmit={createAlert}><h2>Novo alerta</h2><label>Risco relacionado<select name="riskId"><option value="">Sem vínculo</option>{risks.map(x=><option value={x.id} key={x.id}>{x.code} · {x.title}</option>)}</select></label><label>Severidade<select name="severity" defaultValue="WATCH"><option value="INFO">Informativo</option><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label>Título<input name="title" required/></label><label>Mensagem<textarea name="message" required/></label><button className="primaryButton" disabled={busy}>Registrar alerta</button></form>
 </section>
 <section style={{marginTop:18}}><h2>Riscos priorizados</h2><div className="dataGrid">{risks.length===0?<div className="infoCard">Nenhum risco registrado.</div>:risks.map(x=><article className="card" key={x.id}><h2>{x.code} · {x.title}</h2><p><strong>{x.category}</strong> · nível {x.probability*x.impact}/25</p><p>Probabilidade {x.probability} · Impacto {x.impact} · {x.status}</p>{x.mitigation&&<p>{x.mitigation}</p>}<div className="headerActions">{x.status!=="ACTIVE"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("risks",x.id,"ACTIVE")}>Reabrir</button>}{x.status==="ACTIVE"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("risks",x.id,"MITIGATED")}>Marcar mitigado</button>}{x.status!=="CLOSED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("risks",x.id,"CLOSED")}>Encerrar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Alertas recentes</h2><div className="dataGrid">{alerts.length===0?<div className="infoCard">Nenhum alerta registrado.</div>:alerts.slice(0,12).map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.severity}</strong> · {x.status}</p><p>{x.message}</p>{x.monitoringEventId&&<p><strong>Origem:</strong> monitoramento{x.stationCode?` · ${x.stationCode}`:""}{x.stationName?` · ${x.stationName}`:""}</p>}<div className="headerActions">{x.status==="DRAFT"&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>changeStatus("alerts",x.id,"PUBLISHED")}>Publicar</button>}{x.status!=="CLOSED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeStatus("alerts",x.id,"CLOSED")}>Encerrar</button>}</div></article>)}</div></section>
 </main>
}