"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../../lib/release";
import {formatDateTimeBR} from "../../lib/datetime";
import {useRealtimeRefresh} from "../../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
const ops=["consultarProcedimento","gerarProcedimento","incluirDocumento","enviarProcesso","reabrirProcesso","concluirProcesso","consultarDocumento","listarSeries","listarTiposProcedimento","listarUnidades"];
export default function Page(){
 const[connections,setConnections]=useState<Row[]>([]),[links,setLinks]=useState<Row[]>([]),[logs,setLogs]=useState<Row[]>([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[discovered,setDiscovered]=useState<string[]>([]);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[c,p,l]=await Promise.all([request("/api/v1/sei/connections"),request("/api/v1/sei/process-links"),request("/api/v1/sei/operation-logs")]);setConnections(c.items??[]);setLinks(p.items??[]);setLogs(l.items??[]);setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar SEI Cidades.")}},[request]);
 useEffect(()=>{void load()},[load]);
 useRealtimeRefresh(()=>{if(!busy)return load()},true,1000);
 async function perform(fn:()=>Promise<any>,success?:string){setBusy(true);setMsg("");try{const r=await fn();if(success)setMsg(success);await load();return r}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 async function addConnection(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),allowed=ops.filter(x=>d.get("op_"+x)==="on");await perform(()=>request("/api/v1/sei/connections",{method:"POST",body:JSON.stringify({name:String(d.get("name")),baseUrl:String(d.get("baseUrl")),wsdlUrl:String(d.get("wsdlUrl")),systemCode:String(d.get("systemCode")),serviceIdentification:String(d.get("serviceIdentification")||""),unitId:String(d.get("unitId")),active:true,allowedOperations:allowed,config:{processTypeId:String(d.get("processTypeId")||""),documentTypeId:String(d.get("documentTypeId")||""),subjectId:String(d.get("subjectId")||""),accessLevel:String(d.get("accessLevel")||"0"),legalHypothesisId:String(d.get("legalHypothesisId")||"")}})}),"Conexão SEI cadastrada.");f.reset()}
 async function test(id:string){const r=await perform(()=>request("/api/v1/sei/connections/"+id+"/test",{method:"POST",body:"{}"}),"WSDL consultado.");if(r?.operations)setDiscovered(r.operations)}
 async function linkExisting(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(()=>request("/api/v1/sei/process-links",{method:"POST",body:JSON.stringify({connectionId:String(d.get("connectionId")),incidentId:String(d.get("incidentId")||""),protocol:String(d.get("protocol")),processId:String(d.get("processId")||""),url:String(d.get("url")||"")})}),"Processo SEI vinculado ao SIGDEC.");f.reset()}
 async function consult(id:string){await perform(()=>request("/api/v1/sei/process-links/"+id+"/consult",{method:"POST",body:"{}"}),"Processo consultado no SEI.")}
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · SEI CIDADES · {SIGDEC_VERSION_LABEL}</span><h1>Integração SEI Cidades</h1><p>Web Services SOAP com controle de operações, vínculo de processos, consulta e inclusão de relatórios técnicos aprovados.</p></div><div className="headerActions"><Link className="secondaryLink" href="/inteligencia">Relatórios IA</Link><Link className="secondaryLink" href="/administracao">Administração</Link></div></header>
  <nav className="sectionTabs" aria-label="Integrações específicas">
   <Link href="/administracao/integracoes">⇄ Visão geral</Link>
   <Link href="/administracao/integracoes/email">✉ E-mail institucional</Link>
   <Link href="/administracao/geopixel">⌖ GeoPixel</Link>
   <Link className="active" href="/administracao/sei">▤ SEI Cidades</Link>
  </nav>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="warningCard"><strong>Ativação externa necessária</strong><p>O SIGDEC está preparado para o Web Service do SEI, mas a operação real exige cadastro do sistema/serviço no SEI Cidades, identificação do serviço, unidade, IP/servidor autorizado e tipos de processo/documento permitidos. O SIGDEC nunca armazena senha pessoal de servidor.</p></section>
  <section className="statsGrid"><article><strong>{connections.filter(x=>x.active).length}</strong><span>Conexões ativas</span></article><article><strong>{connections.filter(x=>x.lastTestOk).length}</strong><span>WSDL testado com sucesso</span></article><article><strong>{links.length}</strong><span>Processos vinculados</span></article><article><strong>{logs.filter(x=>!x.success).length}</strong><span>Falhas registradas</span></article></section>
  <section className="operationsGrid" style={{marginTop:18}}>
   <form className="incidentForm compactForm" onSubmit={addConnection}><h2>Configurar Web Service SEI</h2><label>Nome<input name="name" required placeholder="SEI Cidades"/></label><label>Endpoint SOAP<input name="baseUrl" type="url" required placeholder="https://.../sei/controlador_ws.php?servico=sei"/></label><label>WSDL<input name="wsdlUrl" type="url" required placeholder="https://.../sei/controlador_ws.php?servico=sei"/></label><div className="formGrid"><label>Sigla do Sistema<input name="systemCode" required placeholder="SIGDEC"/></label><label>Identificação do Serviço<input name="serviceIdentification" type="password" required/></label><label>ID Unidade<input name="unitId" required/></label><label>ID Tipo de Processo<input name="processTypeId"/></label><label>ID Tipo de Documento<input name="documentTypeId"/></label><label>Assunto estruturado<input name="subjectId"/></label><label>Nível de acesso<input name="accessLevel" defaultValue="0"/></label><label>ID hipótese legal<input name="legalHypothesisId"/></label></div><fieldset><legend>Operações autorizadas no SIGDEC</legend><div className="permissionGrid">{ops.map(op=><label key={op}><input type="checkbox" name={"op_"+op} defaultChecked={["consultarProcedimento","gerarProcedimento","incluirDocumento"].includes(op)}/>{op}</label>)}</div></fieldset><button className="primaryButton" disabled={busy}>Salvar conexão</button></form>
   <section><h2>Conexões</h2><div className="dataGrid">{connections.map(x=><article className={x.lastTestOk===false?"warningCard":"card"} key={x.id}><h3>{x.name}</h3><p><strong>{x.active?"Ativa":"Inativa"}</strong> · sistema {x.systemCode} · unidade {x.unitId}</p><p>{x.baseUrl}</p><p>Identificação do serviço: {x.serviceConfigured?"configurada":"não configurada"}</p><p><small>Último teste: {x.lastTestAt?formatDateTimeBR(x.lastTestAt):"não realizado"}{x.lastTestMessage?" · "+x.lastTestMessage:""}</small></p><button className="secondaryButton" disabled={busy} onClick={()=>void test(x.id)}>Testar / descobrir operações</button></article>)}</div>{discovered.length>0&&<article className="infoCard"><strong>Operações descobertas no WSDL:</strong><p>{discovered.join(" · ")}</p></article>}</section>
  </section>
  <section className="detailSection" style={{marginTop:22}}><h2>Vincular processo SEI existente</h2><form className="incidentForm compactForm" onSubmit={linkExisting}><div className="formGrid"><label>Conexão<select name="connectionId" required><option value="">Selecione</option>{connections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Número/NUP SEI<input name="protocol" required/></label><label>ID interno SEI<input name="processId"/></label><label>ID da ocorrência SIGDEC<input name="incidentId"/></label><label>Link público/SEI<input name="url" type="url"/></label></div><button className="primaryButton">Vincular processo</button></form></section>
  <section style={{marginTop:22}}><h2>Processos vinculados</h2><div className="adminTableWrap"><table><thead><tr><th>SEI</th><th>Ocorrência</th><th>Conexão</th><th>Última sync</th><th>Ação</th></tr></thead><tbody>{links.map(x=><tr key={x.id}><td>{x.seiUrl?<a href={x.seiUrl} target="_blank" rel="noreferrer">{x.seiProtocol}</a>:x.seiProtocol}</td><td>{x.incidentProtocol??"—"}</td><td>{x.connectionName}</td><td>{x.lastSyncedAt?formatDateTimeBR(x.lastSyncedAt):"—"}</td><td><button className="secondaryButton" onClick={()=>void consult(x.id)} disabled={busy}>Consultar SEI</button></td></tr>)}</tbody></table></div></section>
  <section style={{marginTop:22}}><h2>Auditoria da integração</h2><div className="adminTableWrap"><table><thead><tr><th>Data</th><th>Operação</th><th>Usuário</th><th>Conexão</th><th>Resultado</th><th>Tempo</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{formatDateTimeBR(x.createdAt)}</td><td>{x.operation}</td><td>{x.actorMatricula} · {x.actorName}</td><td>{x.connectionName}</td><td>{x.success?"OK":x.errorMessage??"Falha"}</td><td>{x.durationMs??0} ms</td></tr>)}</tbody></table></div></section>
 </main>
}
