"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../lib/release";
import {formatDateTimeBR} from "../lib/datetime";
import {useRealtimeRefresh} from "../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
const reportNames:Record<string,string>={FIELD_INSPECTION:"Relatório de vistoria",RISK_ASSESSMENT:"Avaliação de risco",EMERGENCY:"Relatório emergencial",DAMAGE:"Relatório de danos",INTERDICTION:"Minuta de interdição/medida preventiva",SITREP:"Relatório de situação — SITREP",GENERAL:"Relatório técnico geral"};
export default function Page(){
 const[incidents,setIncidents]=useState<Row[]>([]),[reports,setReports]=useState<Row[]>([]),[selectedIncident,setSelectedIncident]=useState(""),[selected,setSelected]=useState<Row|null>(null);
 const[seiConnections,setSeiConnections]=useState<Row[]>([]),[seiLinks,setSeiLinks]=useState<Row[]>([]),[seiConnectionId,setSeiConnectionId]=useState(""),[seiLinkId,setSeiLinkId]=useState("");
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[draft,setDraft]=useState("");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[i,r]=await Promise.all([request("/api/v1/incidents?limit=100"),request("/api/v1/ai/reports")]);setIncidents(i.items??[]);setReports(r.items??[]);setSelectedIncident(current=>current||new URLSearchParams(location.search).get("incidentId")||i.items?.[0]?.id||"");setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar Inteligência SIGDEC.")}},[request]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{void (async()=>{try{const [c,p]=await Promise.all([fetch(API+"/api/v1/sei/connections",{credentials:"include"}),fetch(API+"/api/v1/sei/process-links",{credentials:"include"})]);if(c.ok){const b=await c.json();setSeiConnections(b.items??[]);setSeiConnectionId(current=>current||b.items?.[0]?.id||"")}if(p.ok){const b=await p.json();setSeiLinks(b.items??[]);setSeiLinkId(current=>current||b.items?.[0]?.id||"")}}catch{}})()},[]);
 useRealtimeRefresh(()=>{if(!busy&&!selected)return load()},true,10000);
 async function open(id:string){setBusy(true);try{const r=await request("/api/v1/ai/reports/"+id);setSelected(r);setDraft(r.draftText??"")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao abrir relatório.")}finally{setBusy(false)}}
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);if(!selectedIncident)return;setBusy(true);setMsg("Gerando minuta assistida...");try{const r=await request("/api/v1/ai/reports/generate",{method:"POST",body:JSON.stringify({incidentId:selectedIncident,reportType:String(d.get("reportType")),title:String(d.get("title")||"")||undefined,additionalInstructions:String(d.get("instructions")||"")})});setMsg(r.result==="SUCCEEDED"?"Minuta gerada com IA. Revise integralmente antes de aprovar.":"IA externa indisponível/não configurada: o SIGDEC gerou uma minuta determinística para revisão.");await load();await open(r.id)}catch(e){setMsg(e instanceof Error?e.message:"Falha ao gerar minuta.")}finally{setBusy(false)}}
 async function review(status:string){if(!selected)return;setBusy(true);try{const r=await request("/api/v1/ai/reports/"+selected.id+"/review",{method:"PATCH",body:JSON.stringify({status,draftText:draft,reviewNotes:"Revisão realizada na Central de Inteligência SIGDEC."})});setSelected({...selected,...r});setDraft(r.draftText??draft);setMsg(status==="APPROVED"?"Relatório aprovado por usuário autorizado. Agora pode ser encaminhado ao SEI.":"Situação da revisão atualizada.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha na revisão.")}finally{setBusy(false)}}
 async function refreshSei(){
  try{const [cr,pr]=await Promise.all([fetch(API+"/api/v1/sei/connections",{credentials:"include",cache:"no-store"}),fetch(API+"/api/v1/sei/process-links",{credentials:"include",cache:"no-store"})]);if(cr.ok){const b=await cr.json();setSeiConnections(b.items??[]);setSeiConnectionId(current=>current||b.items?.[0]?.id||"")}if(pr.ok){const b=await pr.json();setSeiLinks(b.items??[]);setSeiLinkId(current=>current||b.items?.[0]?.id||"")}}catch{}
 }
 async function createSeiProcess(){
  if(!selected?.incidentId||!seiConnectionId)return;setBusy(true);try{const r=await request("/api/v1/sei/processes/generate",{method:"POST",body:JSON.stringify({connectionId:seiConnectionId,incidentId:selected.incidentId,entityType:"technical_report",entityId:selected.id,specification:selected.title})});setMsg("Processo SEI criado: "+r.seiProtocol);await refreshSei();if(r.id)setSeiLinkId(r.id)}catch(e){setMsg(e instanceof Error?e.message:"Falha ao criar processo SEI.")}finally{setBusy(false)}
 }
 async function sendReportToSei(){
  if(!selected||selected.status!=="APPROVED"||!seiLinkId)return;setBusy(true);try{const r=await request("/api/v1/sei/process-links/"+seiLinkId+"/include-report",{method:"POST",body:JSON.stringify({reportId:selected.id,description:selected.title})});setMsg("Relatório aprovado incluído no SEI"+(r.seiDocumentProtocol?" · documento "+r.seiDocumentProtocol:"")+".");await refreshSei()}catch(e){setMsg(e instanceof Error?e.message:"Falha ao incluir relatório no SEI.")}finally{setBusy(false)}
 }
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC INTELLIGENCE · {SIGDEC_VERSION_LABEL}</span><h1>Inteligência e Relatórios Técnicos</h1><p>Minutas assistidas por IA com contexto operacional, PostGIS, GeoPixel e base normativa. Toda conclusão exige revisão humana.</p></div><div className="headerActions"><Link className="secondaryLink" href="/administracao/base-legal">Base legal</Link><Link className="secondaryLink" href="/administracao/sei">SEI Cidades</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="warningCard"><strong>Governança da IA</strong><p>A IA não assina, interdita, evacua, altera prioridade, atribui responsabilidade ou emite conclusão técnica definitiva. Ela produz minuta. O servidor/responsável habilitado deve conferir fatos, medições, imagens, legislação vigente e conclusão antes da aprovação.</p></section>
  <section className="operationsGrid" style={{marginTop:18}}>
   <form className="incidentForm compactForm" onSubmit={generate}><h2>Nova minuta técnica</h2><label>Ocorrência<select value={selectedIncident} onChange={e=>setSelectedIncident(e.target.value)} required><option value="">Selecione</option>{incidents.map(x=><option key={x.id} value={x.id}>{x.protocol} · {x.summary}</option>)}</select></label><label>Tipo<select name="reportType">{Object.entries(reportNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Título opcional<input name="title"/></label><label>Orientação adicional ao assistente<textarea name="instructions" placeholder="Ex.: enfatizar condições de drenagem e necessidade de vistoria ambiental. Não use para inserir fatos não registrados."/></label><button className="primaryButton" disabled={busy||!selectedIncident}>Gerar minuta assistida</button></form>
   <section><h2>Relatórios recentes</h2><div className="fieldIncidentList">{reports.map(x=><button type="button" className={"fieldIncident "+(selected?.id===x.id?"fieldIncidentSelected":"")} key={x.id} onClick={()=>void open(x.id)}><span className="priorityBadge">{x.status==="APPROVED"?"✓":"AI"}</span><span><strong>{x.title}</strong><small>{x.protocol??"Sem ocorrência"} · {reportNames[x.reportType]??x.reportType}</small><small>{x.status} · {x.aiAssisted?"IA "+(x.aiModel??""):"motor determinístico"} · {formatDateTimeBR(x.createdAt)}</small></span></button>)}</div></section>
  </section>
  {selected&&<section className="detailSection" style={{marginTop:22}}><div className="listHeader"><div><span className="eyebrow">MINUTA TÉCNICA · {selected.status}</span><h2>{selected.title}</h2><p>{selected.protocol??"Sem protocolo"} · {selected.aiProvider}{selected.aiModel?" · "+selected.aiModel:""}</p></div><div className="headerActions"><button className="secondaryButton" onClick={()=>void review("IN_REVIEW")} disabled={busy}>Marcar em revisão</button><button className="primaryButton" onClick={()=>void review("APPROVED")} disabled={busy}>Aprovar revisão humana</button><button className="secondaryButton" onClick={()=>void review("REJECTED")} disabled={busy}>Rejeitar</button></div></div><label>Texto da minuta<textarea style={{minHeight:520}} value={draft} onChange={e=>setDraft(e.target.value)}/></label><p><small>Alterações humanas ficam registradas na auditoria. Somente situação APPROVED habilita envio ao SEI.</small></p>
   {seiConnections.length>0&&<section className="card" style={{marginTop:18}}><span className="eyebrow">SEI CIDADES</span><h3>Protocolar relatório aprovado</h3><div className="formGrid"><label>Conexão SEI<select value={seiConnectionId} onChange={e=>setSeiConnectionId(e.target.value)}>{seiConnections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Processo vinculado<select value={seiLinkId} onChange={e=>setSeiLinkId(e.target.value)}><option value="">Selecione ou crie</option>{seiLinks.filter(x=>!selected.incidentId||!x.incidentId||x.incidentId===selected.incidentId).map(x=><option key={x.id} value={x.id}>{x.seiProtocol} · {x.connectionName}</option>)}</select></label></div><div className="headerActions"><button className="secondaryButton" type="button" disabled={busy||!selected.incidentId||!seiConnectionId} onClick={()=>void createSeiProcess()}>Criar processo SEI</button><button className="primaryButton" type="button" disabled={busy||selected.status!=="APPROVED"||!seiLinkId} onClick={()=>void sendReportToSei()}>Incluir relatório aprovado no SEI</button></div></section>}
  </section>}
 </main>
}
