"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../../lib/release";
import {formatDateTimeBR} from "../../lib/datetime";
import {useRealtimeRefresh} from "../../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
export default function Page(){
 const[status,setStatus]=useState<Row>({}),[connections,setConnections]=useState<Row[]>([]),[layers,setLayers]=useState<Row[]>([]),[runs,setRuns]=useState<Row[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[discovery,setDiscovery]=useState<Row|null>(null),[selectedConnection,setSelectedConnection]=useState("");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[s,c,l,r]=await Promise.all([request("/api/v1/geopixel/status"),request("/api/v1/geopixel/connections"),request("/api/v1/geopixel/layers"),request("/api/v1/geopixel/sync-runs")]);setStatus(s);setConnections(c.items??[]);setLayers(l.items??[]);setRuns(r.items??[]);setSelectedConnection(current=>current||c.items?.[0]?.id||"");setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar GeoPixel.")}},[request]);
 useEffect(()=>{void load()},[load]);useRealtimeRefresh(()=>{if(!busy)return load()},true,15000);
 async function perform(fn:()=>Promise<any>,success?:string){setBusy(true);setMsg("");try{const r=await fn();if(success)setMsg(success);await load();return r}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 const json=(value:FormDataEntryValue|null)=>{const s=String(value??"").trim();if(!s)return{};try{return JSON.parse(s)}catch{throw new Error("JSON de mapeamento/parâmetros inválido.")}};
 async function addConnection(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(()=>request("/api/v1/geopixel/connections",{method:"POST",body:JSON.stringify({
  name:String(d.get("name")),portalUrl:String(d.get("portalUrl")||""),apiBaseUrl:String(d.get("apiBaseUrl")||""),wmsUrl:String(d.get("wmsUrl")||""),wfsUrl:String(d.get("wfsUrl")||""),
  authType:String(d.get("authType")),username:String(d.get("username")||""),secret:String(d.get("secret")||""),apiKeyHeader:String(d.get("apiKeyHeader")||"x-api-key"),
  syncIntervalMinutes:Number(d.get("syncIntervalMinutes")||60),active:true,config:{municipality:"Ubatuba",purpose:"SIGDEC full territorial integration"}
 })}),"Conexão GeoPixel cadastrada.");f.reset()}
 async function testConnection(id:string){await perform(()=>request("/api/v1/geopixel/connections/"+id+"/test",{method:"POST",body:"{}"}),"Teste de conexão concluído.")}
 async function discover(id:string){const result=await perform(()=>request("/api/v1/geopixel/connections/"+id+"/discover"));if(result)setDiscovery(result)}
 async function addLayer(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(()=>request("/api/v1/geopixel/layers",{method:"POST",body:JSON.stringify({
  connectionId:String(d.get("connectionId")),code:String(d.get("code")),title:String(d.get("title")),sourceType:String(d.get("sourceType")),
  remoteLayerName:String(d.get("remoteLayerName")||""),resourcePath:String(d.get("resourcePath")||""),category:String(d.get("category")),
  direction:String(d.get("direction")),localTarget:String(d.get("localTarget")),attributeMap:json(d.get("attributeMap")),requestParams:json(d.get("requestParams")),
  exportMethod:String(d.get("exportMethod")),remoteIdProperty:String(d.get("remoteIdProperty")||"id"),active:true
 })}),"Camada GeoPixel cadastrada.");f.reset()}
 async function syncLayer(id:string){await perform(()=>request("/api/v1/geopixel/layers/"+id+"/sync",{method:"POST",body:"{}"}),"Sincronização da camada concluída.")}
 async function syncAll(){await perform(()=>request("/api/v1/geopixel/sync-all",{method:"POST",body:"{}"}),"Sincronização geral concluída.")}
 const activeFeatures=Number(status.features?.active??0),failed24h=Number(status.sync?.failed24h??0);
 const selected=useMemo(()=>connections.find(x=>x.id===selectedConnection),[connections,selectedConnection]);
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · GEOPIXEL · {SIGDEC_VERSION_LABEL}</span><h1>Integração GeoPixel</h1><p>Integração territorial corporativa: REST/GeoJSON, WFS, WMS, PostGIS, sincronização, espelhamento em módulos do SIGDEC e contexto geográfico de ocorrências.</p></div><div className="headerActions"><Link className="secondaryLink" href="/campo?monitor=1">Mapa multicamadas</Link><Link className="secondaryLink" href="/administracao">Administração</Link></div></header>
  {msg&&<section className={failed24h?"warningCard":"infoCard"}>{msg}</section>}
  <section className="statsGrid"><article><strong>{status.connections?.active??0}</strong><span>Conexões ativas</span></article><article><strong>{status.layers?.active??0}</strong><span>Camadas ativas</span></article><article><strong>{activeFeatures}</strong><span>Feições sincronizadas</span></article><article className={failed24h?"warningCard":""}><strong>{failed24h}</strong><span>Falhas de sync em 24h</span></article></section>

  <section className="operationsGrid" style={{marginTop:18}}>
   <form className="incidentForm compactForm" onSubmit={addConnection}><h2>Conexão GeoPixel</h2><label>Nome<input name="name" required defaultValue="GeoPixel Ubatuba"/></label><label>Portal<input name="portalUrl" type="url" defaultValue="https://monitor-ubatuba.geopixel.com.br/monitor/"/></label><label>API base<input name="apiBaseUrl" type="url" placeholder="Endpoint REST fornecido pela GeoPixel"/></label><label>WFS<input name="wfsUrl" type="url" placeholder="Endpoint WFS, se disponibilizado"/></label><label>WMS<input name="wmsUrl" type="url" placeholder="Endpoint WMS, se disponibilizado"/></label><div className="formGrid"><label>Autenticação<select name="authType"><option>NONE</option><option>BEARER</option><option>API_KEY</option><option>BASIC</option></select></label><label>Usuário<input name="username"/></label><label>Token/senha<input name="secret" type="password" autoComplete="new-password"/></label><label>Header API key<input name="apiKeyHeader" defaultValue="x-api-key"/></label><label>Sincronizar a cada (min)<input name="syncIntervalMinutes" type="number" min="5" max="10080" defaultValue="60"/></label></div><button className="primaryButton" disabled={busy}>Cadastrar conexão</button></form>
   <section><h2>Conexões configuradas</h2><div className="dataGrid">{connections.map(x=><article className={x.lastTestOk===false?"warningCard":"card"} key={x.id}><h3>{x.name}</h3><p><strong>{x.active?"Ativa":"Inativa"}</strong> · {x.authType} · credencial {x.secretConfigured?"configurada":"não configurada"}</p><p>{x.apiBaseUrl||x.wfsUrl||x.wmsUrl||x.portalUrl}</p><p><small>Teste: {x.lastTestAt?formatDateTimeBR(x.lastTestAt):"não realizado"}{x.lastTestMessage?" · "+x.lastTestMessage:""}</small></p><div className="headerActions"><button className="secondaryButton" onClick={()=>void testConnection(x.id)} disabled={busy}>Testar</button><button className="secondaryButton" onClick={()=>void discover(x.id)} disabled={busy}>Descobrir camadas</button></div></article>)}</div></section>
  </section>

  {discovery&&<section className="detailSection" style={{marginTop:18}}><h2>Descoberta OGC</h2><p><strong>WFS:</strong> {(discovery.wfs??[]).length} camada(s) · <strong>WMS:</strong> {(discovery.wms??[]).length} camada(s)</p>{(discovery.notes??[]).map((x:string,i:number)=><p key={i}><small>{x}</small></p>)}<div className="dataGrid"><article className="card"><h3>WFS</h3><p style={{wordBreak:"break-word"}}>{(discovery.wfs??[]).join(" · ")||"Nenhuma camada descoberta."}</p></article><article className="card"><h3>WMS</h3><p style={{wordBreak:"break-word"}}>{(discovery.wms??[]).join(" · ")||"Nenhuma camada descoberta."}</p></article></div></section>}

  <section style={{marginTop:22}}><div className="listHeader"><div><h2>Mapeamento de camadas</h2><p>Cada camada pode permanecer como referência territorial ou alimentar automaticamente Riscos/PMRR, Infraestruturas, Sirenes ou Abrigos.</p></div><button className="primaryButton" onClick={()=>void syncAll()} disabled={busy||layers.length===0}>Sincronizar tudo</button></div>
   <form className="incidentForm compactForm" onSubmit={addLayer}><div className="formGrid"><label>Conexão<select name="connectionId" value={selectedConnection} onChange={e=>setSelectedConnection(e.target.value)} required><option value="">Selecione</option>{connections.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Código local<input name="code" required placeholder="zoneamento"/></label><label>Título<input name="title" required placeholder="Zoneamento urbano"/></label><label>Origem<select name="sourceType"><option>REST_GEOJSON</option><option>WFS</option><option>WMS_REFERENCE</option></select></label><label>Camada remota<input name="remoteLayerName" placeholder="workspace:camada"/></label><label>Recurso REST<input name="resourcePath" placeholder="/api/camadas/zoneamento"/></label><label>Categoria<select name="category"><option>CADASTRAL</option><option>ZONING</option><option>URBANISM</option><option>HOUSING</option><option>ENVIRONMENT</option><option>APP</option><option>RISK</option><option>HYDROGRAPHY</option><option>DRAINAGE</option><option>ROAD</option><option>INFRASTRUCTURE</option><option>BUILDING</option><option>LAND_USE</option><option>VEGETATION</option><option>MONITORING</option><option>OTHER</option></select></label><label>Direção<select name="direction"><option>IMPORT</option><option>REFERENCE</option><option>BIDIRECTIONAL</option><option>EXPORT</option></select></label><label>Espelhar no SIGDEC<select name="localTarget"><option>REFERENCE_ONLY</option><option>RISK_AREA</option><option>CRITICAL_INFRASTRUCTURE</option><option>WARNING_ASSET</option><option>SHELTER</option></select></label><label>Método de exportação<select name="exportMethod"><option>POST</option><option>PUT</option><option>PATCH</option></select></label><label>Campo ID remoto<input name="remoteIdProperty" defaultValue="id"/></label></div><label>Mapeamento de atributos (JSON)<textarea name="attributeMap" placeholder={'{"code":"codigo","name":"nome","neighborhood":"bairro"}'}/></label><label>Parâmetros adicionais (JSON)<textarea name="requestParams" placeholder={'{"srsName":"EPSG:4326"}'}/></label><button className="primaryButton" disabled={busy||!selected}>Cadastrar camada</button></form>
  </section>

  <section style={{marginTop:18}}><h2>Camadas integradas</h2><div className="dataGrid">{layers.map(x=><article className={x.lastSyncStatus==="FAILED"?"warningCard":"card"} key={x.id}><h3>{x.title}</h3><p><strong>{x.category}</strong> · {x.sourceType} · {x.direction} · alvo {x.localTarget}</p><p>{x.remoteLayerName||x.resourcePath||"Referência visual"} · {x.featureCount} feição(ões)</p><p><small>Última sync: {x.lastSyncAt?formatDateTimeBR(x.lastSyncAt):"nunca"}{x.lastSyncMessage?" · "+x.lastSyncMessage:""}</small></p>{x.sourceType!=="WMS_REFERENCE"&&["IMPORT","BIDIRECTIONAL"].includes(x.direction)&&<button className="secondaryButton" onClick={()=>void syncLayer(x.id)} disabled={busy}>Sincronizar agora</button>}</article>)}</div></section>

  <section style={{marginTop:22}}><h2>Histórico de sincronização</h2><div className="adminTableWrap"><table><thead><tr><th>Início</th><th>Conexão</th><th>Camada</th><th>Direção</th><th>Status</th><th>Recebidas</th><th>Inseridas/Atualizadas</th><th>Mensagem</th></tr></thead><tbody>{runs.map(x=><tr key={x.id}><td>{formatDateTimeBR(x.startedAt)}</td><td>{x.connectionName}</td><td>{x.layerTitle??"—"}</td><td>{x.direction}</td><td>{x.status}</td><td>{x.featuresReceived}</td><td>{x.featuresInserted}/{x.featuresUpdated}</td><td>{x.message??"—"}</td></tr>)}</tbody></table></div></section>
 </main>
}
