"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Station={id:string;code:string;name:string;stationType:string;provider?:string|null;externalId?:string|null};
type Reading={id:number;stationId:string;stationName:string;stationCode:string;metric:string;value:string|number;unit:string;source:string;measuredAt:string};
type Threshold={id:string;stationId:string;stationName:string;metric:string;severity:string;comparison:string;thresholdValue:string|number;unit:string;title:string;guidance?:string|null;active:boolean};
type MonitoringEvent={id:string;stationId:string;stationName:string;stationCode:string;severity:string;metric:string;observedValue:string|number;thresholdValue:string|number;unit:string;title:string;guidance?:string|null;status:string;createdAt:string};
export default function Page(){
 const [stations,setStations]=useState<Station[]>([]),[readings,setReadings]=useState<Reading[]>([]),[thresholds,setThresholds]=useState<Threshold[]>([]),[events,setEvents]=useState<MonitoringEvent[]>([]);
 const [status,setStatus]=useState("Carregando..."),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`${API}${path}`,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";return null}if(!r.ok)throw new Error("Não foi possível concluir a operação.");return r.json()},[]);
 const load=useCallback(async()=>{try{const [s,r,t,e]=await Promise.all([request("/api/v1/monitoring/stations"),request("/api/v1/monitoring/readings/latest"),request("/api/v1/monitoring/thresholds"),request("/api/v1/monitoring/events")]);if(s)setStations(s.items??[]);if(r)setReadings(r.items??[]);if(t)setThresholds(t.items??[]);if(e)setEvents(e.items??[]);setStatus("")}catch{setStatus("Não foi possível carregar os dados de monitoramento.")}},[request]);
 useEffect(()=>{load()},[load]);
 async function createThreshold(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/monitoring/thresholds",{method:"POST",body:JSON.stringify({stationId:String(f.get("stationId")),metric:String(f.get("metric")),severity:String(f.get("severity")),comparison:String(f.get("comparison")),thresholdValue:Number(f.get("thresholdValue")),unit:String(f.get("unit")),title:String(f.get("title")),guidance:String(f.get("guidance")||"")||undefined})});form.reset();setMessage("Limiar registrado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar limiar.")}finally{setBusy(false)}}
 async function createReading(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);const raw=String(f.get("measuredAt"));try{await request(`/api/v1/monitoring/stations/${String(f.get("stationId"))}/readings`,{method:"POST",body:JSON.stringify({measuredAt:new Date(raw).toISOString(),metric:String(f.get("metric")),value:Number(f.get("value")),unit:String(f.get("unit")),source:"manual"})});form.reset();setMessage("Leitura registrada e avaliada.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar leitura.")}finally{setBusy(false)}}
 async function changeEvent(id:string,eventStatus:"ACKNOWLEDGED"|"CLOSED"){setBusy(true);setMessage("");try{await request(`/api/v1/monitoring/events/${id}/status`,{method:"PATCH",body:JSON.stringify({status:eventStatus})});setMessage("Evento atualizado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar evento.")}finally{setBusy(false)}}
 return <main className="shell moduleShell"><header className="listHeader"><div><span className="eyebrow">SIGDEC · DEFESA CIVIL · UBATUBA</span><h1>Monitoramento Operacional</h1><p>Estações, leituras, limiares e eventos para apoio à decisão.</p></div><div className="headerActions"><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
 {status&&<section className="infoCard">{status}</section>}{message&&<p className="formMessage">{message}</p>}
 <section className="operationsGrid">
  <form className="incidentForm compactForm" onSubmit={createThreshold}><h2>Novo limiar</h2><label>Estação<select name="stationId" required><option value="">Selecione</option>{stations.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Métrica<input name="metric" required placeholder="chuva_1h, nivel_rio..."/></label><div className="formGrid"><label>Severidade<select name="severity" defaultValue="WATCH"><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label>Comparação<select name="comparison" defaultValue="GTE"><option value="GTE">Maior ou igual</option><option value="LTE">Menor ou igual</option></select></label></div><div className="formGrid"><label>Valor<input name="thresholdValue" type="number" step="any" required/></label><label>Unidade<input name="unit" required placeholder="mm, m, °C..."/></label></div><label>Título<input name="title" required/></label><label>Orientação<textarea name="guidance"/></label><button className="primaryButton" disabled={busy||stations.length===0}>Salvar limiar</button></form>
  <form className="incidentForm compactForm" onSubmit={createReading}><h2>Registrar leitura manual</h2><label>Estação<select name="stationId" required><option value="">Selecione</option>{stations.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Data e hora<input name="measuredAt" type="datetime-local" required/></label><label>Métrica<input name="metric" required placeholder="chuva_1h, nivel_rio..."/></label><div className="formGrid"><label>Valor<input name="value" type="number" step="any" required/></label><label>Unidade<input name="unit" required/></label></div><button className="primaryButton" disabled={busy||stations.length===0}>Registrar e avaliar</button></form>
 </section>
 <section style={{marginTop:18}}><h2>Eventos operacionais</h2><div className="dataGrid">{events.length===0?<div className="infoCard">Nenhum evento gerado pelos limiares.</div>:events.slice(0,24).map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.severity}</strong> · {x.status} · {x.stationCode} · {x.stationName}</p><p>{x.metric}: <strong>{x.observedValue} {x.unit}</strong> · limiar {x.thresholdValue} {x.unit}</p>{x.guidance&&<p>{x.guidance}</p>}<div className="headerActions">{x.status==="OPEN"&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>changeEvent(x.id,"ACKNOWLEDGED")}>Reconhecer</button>}{x.status!=="CLOSED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeEvent(x.id,"CLOSED")}>Encerrar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Últimas leituras</h2><div className="dataGrid">{readings.length===0?<div className="infoCard">Nenhuma leitura registrada.</div>:readings.map(x=><article className="card" key={`${x.stationId}-${x.metric}`}><h2>{x.stationName}</h2><p><strong>{x.metric}</strong> · {x.value} {x.unit}</p><p>{new Date(x.measuredAt).toLocaleString("pt-BR")} · {x.source}</p></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Limiares configurados</h2><div className="dataGrid">{thresholds.length===0?<div className="infoCard">Nenhum limiar configurado.</div>:thresholds.map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.severity}</strong> · {x.stationName}</p><p>{x.metric} {x.comparison==="GTE"?"≥":"≤"} {x.thresholdValue} {x.unit}</p>{x.guidance&&<p>{x.guidance}</p>}</article>)}</div></section>
 <section style={{marginTop:18}}><h2>Estações</h2><div className="dataGrid">{stations.length===0&&!status?<div className="infoCard">Nenhuma estação cadastrada.</div>:stations.map(x=><article className="card" key={x.id}><h2>{x.name}</h2><p><strong>{x.code}</strong> · {x.stationType}</p><p>{x.provider??"Fonte não informada"}{x.externalId?` · ID ${x.externalId}`:""}</p></article>)}</div></section>
 </main>
}