"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Station={id:string;code:string;name:string;stationType:string;provider?:string|null;externalId?:string|null};
type Reading={id:number;stationId:string;stationName:string;stationCode:string;metric:string;value:string|number;unit:string;source:string;measuredAt:string};
type Threshold={id:string;stationId:string;stationName:string;metric:string;severity:string;comparison:string;thresholdValue:string|number;unit:string;title:string;guidance?:string|null;active:boolean;protocolVersionId?:string|null;protocolCode?:string|null;protocolVersionNo?:number|null};
type MonitoringEvent={id:string;stationId:string;stationName:string;stationCode:string;severity:string;metric:string;observedValue:string|number;thresholdValue:string|number;unit:string;title:string;guidance?:string|null;status:string;createdAt:string;alertId?:string|null;alertStatus?:string|null;protocolVersionId?:string|null;protocolCode?:string|null;protocolVersionNo?:number|null;protocolSteps?:string[]|null};
type IngestKey={id:string;name:string;active:boolean;createdAt:string;lastUsedAt?:string|null;revokedAt?:string|null};
type Protocol={id:string;code:string;title:string;category:string;activeVersionId?:string|null;activeVersionNo?:number|null;severity?:string|null;guidance?:string|null;steps?:string[]|null};
type ProtocolVersion={id:string;versionNo:number;severity?:string|null;triggerSummary?:string|null;guidance?:string|null;steps:string[];status:string;changeSummary?:string|null;createdAt:string;activatedAt?:string|null};
type ProtocolTemplate={id:string;code:string;cobradeCode:string;title:string;category:string;severity?:string|null;triggerSummary?:string|null;guidance?:string|null;steps:string[];organizationId?:string|null};
type Connector={id:string;stationId:string;stationCode:string;stationName:string;providerCode:string;displayName:string;mode:string;status:string;externalReference?:string|null;lastSuccessAt?:string|null;lastErrorAt?:string|null;lastError?:string|null};
type CobradeCatalogItem={code:string;name:string;group?:string|null;subgroup?:string|null;type?:string|null;subtype?:string|null;sourceName?:string|null;sourceVersion?:string|null};
export default function Page(){
 const [stations,setStations]=useState<Station[]>([]),[readings,setReadings]=useState<Reading[]>([]),[thresholds,setThresholds]=useState<Threshold[]>([]),[events,setEvents]=useState<MonitoringEvent[]>([]),[protocols,setProtocols]=useState<Protocol[]>([]),[keys,setKeys]=useState<IngestKey[]>([]),[versions,setVersions]=useState<ProtocolVersion[]>([]),[protocolTemplates,setProtocolTemplates]=useState<ProtocolTemplate[]>([]),[connectors,setConnectors]=useState<Connector[]>([]),[cobradeCatalog,setCobradeCatalog]=useState<CobradeCatalogItem[]>([]);
 const [status,setStatus]=useState("Carregando..."),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[newToken,setNewToken]=useState(""),[selectedKeyStation,setSelectedKeyStation]=useState(""),[selectedProtocolId,setSelectedProtocolId]=useState("");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`${API}${path}`,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";return null}if(!r.ok)throw new Error("Não foi possível concluir a operação.");return r.json()},[]);
 const load=useCallback(async()=>{try{const [s,r,t,e,p,pt,cx,cc]=await Promise.all([request("/api/v1/monitoring/stations"),request("/api/v1/monitoring/readings/latest"),request("/api/v1/monitoring/thresholds"),request("/api/v1/monitoring/events"),request("/api/v1/monitoring/protocols"),request("/api/v1/monitoring/protocol-templates"),request("/api/v1/monitoring/connectors"),request("/api/v1/cobrade/catalog")]);if(s)setStations(s.items??[]);if(r)setReadings(r.items??[]);if(t)setThresholds(t.items??[]);if(e)setEvents(e.items??[]);if(p)setProtocols(p.items??[]);if(pt)setProtocolTemplates(pt.items??[]);if(cx)setConnectors(cx.items??[]);if(cc)setCobradeCatalog(cc.items??[]);setStatus("")}catch{setStatus("Não foi possível carregar os dados de monitoramento.")}},[request]);
 useEffect(()=>{load()},[load]);
 async function loadKeys(stationId:string){if(!stationId){setKeys([]);return}const b=await request(`/api/v1/monitoring/stations/${stationId}/ingest-keys`);setKeys(b?.items??[])}
 async function loadVersions(protocolId:string){if(!protocolId){setVersions([]);return}const b=await request(`/api/v1/monitoring/protocols/${protocolId}/versions`);setVersions(b?.items??[])}
 useEffect(()=>{void loadKeys(selectedKeyStation).catch(()=>setKeys([]))},[selectedKeyStation]);
 useEffect(()=>{void loadVersions(selectedProtocolId).catch(()=>setVersions([]))},[selectedProtocolId]);
 async function createThreshold(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/monitoring/thresholds",{method:"POST",body:JSON.stringify({stationId:String(f.get("stationId")),metric:String(f.get("metric")),severity:String(f.get("severity")),comparison:String(f.get("comparison")),thresholdValue:Number(f.get("thresholdValue")),unit:String(f.get("unit")),title:String(f.get("title")),guidance:String(f.get("guidance")||"")||undefined,protocolVersionId:String(f.get("protocolVersionId")||"")||undefined})});form.reset();setMessage("Limiar registrado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar limiar.")}finally{setBusy(false)}}
 async function createReading(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);const raw=String(f.get("measuredAt"));try{await request(`/api/v1/monitoring/stations/${String(f.get("stationId"))}/readings`,{method:"POST",body:JSON.stringify({measuredAt:new Date(raw).toISOString(),metric:String(f.get("metric")),value:Number(f.get("value")),unit:String(f.get("unit")),source:"manual"})});form.reset();setMessage("Leitura registrada e avaliada.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar leitura.")}finally{setBusy(false)}}
 async function changeEvent(id:string,eventStatus:"ACKNOWLEDGED"|"CLOSED"){setBusy(true);setMessage("");try{await request(`/api/v1/monitoring/events/${id}/status`,{method:"PATCH",body:JSON.stringify({status:eventStatus})});setMessage("Evento atualizado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar evento.")}finally{setBusy(false)}}
 async function createAlertDraft(id:string){setBusy(true);setMessage("");try{const b=await request(`/api/v1/monitoring/events/${id}/alert-draft`,{method:"POST",body:"{}"});setMessage(`Rascunho de alerta criado: ${b?.id??""}`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao criar rascunho.")}finally{setBusy(false)}}
 async function createIngestKey(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");setNewToken("");const form=e.currentTarget,f=new FormData(form),stationId=String(f.get("stationId"));try{const b=await request(`/api/v1/monitoring/stations/${stationId}/ingest-keys`,{method:"POST",body:JSON.stringify({name:String(f.get("name"))})});setNewToken(String(b?.token??""));setSelectedKeyStation(stationId);setMessage("Chave criada. Copie e armazene agora: ela não será exibida novamente.");form.reset();await loadKeys(stationId)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao criar chave.")}finally{setBusy(false)}}
 async function revokeKey(id:string){setBusy(true);setMessage("");try{await request(`/api/v1/monitoring/ingest-keys/${id}/revoke`,{method:"POST",body:"{}"});setMessage("Chave revogada imediatamente.");await loadKeys(selectedKeyStation)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao revogar chave.")}finally{setBusy(false)}}
 async function rotateKey(id:string){setBusy(true);setMessage("");setNewToken("");try{const b=await request(`/api/v1/monitoring/ingest-keys/${id}/rotate`,{method:"POST",body:"{}"});setNewToken(String(b?.token??""));setMessage("Chave rotacionada. A anterior foi revogada; copie o novo token agora.");await loadKeys(selectedKeyStation)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao rotacionar chave.")}finally{setBusy(false)}}
 async function createProtocol(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{const b=await request("/api/v1/monitoring/protocols",{method:"POST",body:JSON.stringify({code:String(f.get("code")),title:String(f.get("title")),category:String(f.get("category")||"MONITORING")})});setSelectedProtocolId(String(b?.id??""));setMessage("Protocolo criado. Crie agora a primeira versão.");form.reset();await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao criar protocolo.")}finally{setBusy(false)}}
 async function createProtocolVersion(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form),protocolId=String(f.get("protocolId"));try{const steps=String(f.get("steps")||"").split("\n").map(x=>x.trim()).filter(Boolean);await request(`/api/v1/monitoring/protocols/${protocolId}/versions`,{method:"POST",body:JSON.stringify({severity:String(f.get("severity")||"")||undefined,triggerSummary:String(f.get("triggerSummary")||"")||undefined,guidance:String(f.get("guidance")||"")||undefined,steps,changeSummary:String(f.get("changeSummary")||"")||undefined})});setSelectedProtocolId(protocolId);setMessage("Versão criada em rascunho.");form.reset();await loadVersions(protocolId)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao criar versão.")}finally{setBusy(false)}}
 async function activateVersion(protocolId:string,versionId:string){setBusy(true);setMessage("");try{await request(`/api/v1/monitoring/protocols/${protocolId}/versions/${versionId}/activate`,{method:"POST",body:"{}"});setMessage("Versão ativada. A anterior foi aposentada automaticamente.");await Promise.all([load(),loadVersions(protocolId)])}catch(e){setMessage(e instanceof Error?e.message:"Falha ao ativar versão.")}finally{setBusy(false)}}
 async function createProtocolTemplate(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{const steps=String(f.get("steps")||"").split("\n").map(x=>x.trim()).filter(Boolean);await request("/api/v1/monitoring/protocol-templates",{method:"POST",body:JSON.stringify({code:String(f.get("code")),cobradeCode:String(f.get("cobradeCode")),title:String(f.get("title")),category:String(f.get("category")||"MONITORING"),severity:String(f.get("severity")||"")||undefined,triggerSummary:String(f.get("triggerSummary")||"")||undefined,guidance:String(f.get("guidance")||"")||undefined,steps})});form.reset();setMessage("Modelo COBRADE criado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao criar modelo COBRADE.")}finally{setBusy(false)}}
 async function instantiateTemplate(id:string){setBusy(true);setMessage("");try{const b=await request(`/api/v1/monitoring/protocol-templates/${id}/instantiate`,{method:"POST",body:"{}"});setSelectedProtocolId(String(b?.protocol?.id??""));setMessage("Protocolo criado a partir do modelo COBRADE em versão rascunho.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao instanciar modelo.")}finally{setBusy(false)}}
 async function createConnector(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{await request("/api/v1/monitoring/connectors",{method:"POST",body:JSON.stringify({stationId:String(f.get("stationId")),providerCode:String(f.get("providerCode")),displayName:String(f.get("displayName")),mode:String(f.get("mode")),externalReference:String(f.get("externalReference")||"")||undefined})});form.reset();setMessage("Conector registrado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao registrar conector.")}finally{setBusy(false)}}
 async function changeConnectorStatus(id:string,status:string){setBusy(true);setMessage("");try{await request(`/api/v1/monitoring/connectors/${id}/status`,{method:"PATCH",body:JSON.stringify({status})});setMessage("Status do conector atualizado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao atualizar conector.")}finally{setBusy(false)}}
 async function importCobrade(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const form=e.currentTarget,f=new FormData(form);try{const b=await request("/api/v1/cobrade/catalog/import",{method:"POST",body:JSON.stringify({csv:String(f.get("csv")),sourceName:String(f.get("sourceName")||"")||undefined,sourceVersion:String(f.get("sourceVersion")||"")||undefined})});setMessage(`Catálogo COBRADE importado: ${b?.imported??0} registro(s).`);form.reset();await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao importar catálogo COBRADE.")}finally{setBusy(false)}}
 return <main className="shell moduleShell"><header className="listHeader"><div><span className="eyebrow">SIGDEC · DEFESA CIVIL · UBATUBA</span><h1>Monitoramento Operacional</h1><p>Estações, leituras, limiares e eventos para apoio à decisão.</p></div><div className="headerActions"><Link className="secondaryLink" href="/campo">Mapa / SITREP</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
 {status&&<section className="infoCard">{status}</section>}{message&&<p className="formMessage">{message}</p>}
 <section className="operationsGrid">
  <form className="incidentForm compactForm" onSubmit={createThreshold}><h2>Novo limiar</h2><label>Estação<select name="stationId" required><option value="">Selecione</option>{stations.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Métrica<input name="metric" required placeholder="chuva_1h, nivel_rio..."/></label><div className="formGrid"><label>Severidade<select name="severity" defaultValue="WATCH"><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label>Comparação<select name="comparison" defaultValue="GTE"><option value="GTE">Maior ou igual</option><option value="LTE">Menor ou igual</option></select></label></div><div className="formGrid"><label>Valor<input name="thresholdValue" type="number" step="any" required/></label><label>Unidade<input name="unit" required placeholder="mm, m, °C..."/></label></div><label>Protocolo ativo<select name="protocolVersionId"><option value="">Sem protocolo</option>{protocols.filter(x=>x.activeVersionId).map(x=><option value={x.activeVersionId??""} key={x.id}>{x.code} · v{x.activeVersionNo}</option>)}</select></label><label>Título<input name="title" required/></label><label>Orientação<textarea name="guidance"/></label><button className="primaryButton" disabled={busy||stations.length===0}>Salvar limiar</button></form>
  <form className="incidentForm compactForm" onSubmit={createReading}><h2>Registrar leitura manual</h2><label>Estação<select name="stationId" required><option value="">Selecione</option>{stations.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Data e hora<input name="measuredAt" type="datetime-local" required/></label><label>Métrica<input name="metric" required placeholder="chuva_1h, nivel_rio..."/></label><div className="formGrid"><label>Valor<input name="value" type="number" step="any" required/></label><label>Unidade<input name="unit" required/></label></div><button className="primaryButton" disabled={busy||stations.length===0}>Registrar e avaliar</button></form>
  <form className="incidentForm compactForm" onSubmit={createIngestKey}><h2>Integração externa</h2><label>Estação<select name="stationId" required><option value="">Selecione</option>{stations.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Nome da chave<input name="name" required placeholder="Pluviômetro automático, integração fornecedor..."/></label><button className="primaryButton" disabled={busy||stations.length===0}>Gerar chave de ingestão</button>{newToken&&<div className="infoCard"><strong>Token — exibição única</strong><p style={{overflowWrap:"anywhere"}}>{newToken}</p><small>Envie em Authorization: Bearer &lt;token&gt; para POST /api/v1/integrations/monitoring/readings.</small></div>}</form>
  <form className="incidentForm compactForm" onSubmit={createProtocol}><h2>Novo protocolo</h2><label>Código<input name="code" required placeholder="PLUV-001"/></label><label>Título<input name="title" required placeholder="Resposta a chuva intensa"/></label><label>Categoria<input name="category" defaultValue="MONITORING"/></label><button className="primaryButton" disabled={busy}>Criar protocolo</button></form>
  <form className="incidentForm compactForm" onSubmit={createProtocolVersion}><h2>Nova versão de protocolo</h2><label>Protocolo<select name="protocolId" required value={selectedProtocolId} onChange={e=>setSelectedProtocolId(e.target.value)}><option value="">Selecione</option>{protocols.map(x=><option value={x.id} key={x.id}>{x.code} · {x.title}</option>)}</select></label><label>Severidade<select name="severity"><option value="">Não definida</option><option value="INFO">Informativo</option><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label>Gatilho<textarea name="triggerSummary"/></label><label>Orientação<textarea name="guidance"/></label><label>Passos — um por linha<textarea name="steps"/></label><label>Resumo da alteração<input name="changeSummary"/></label><button className="primaryButton" disabled={busy||!selectedProtocolId}>Criar versão em rascunho</button></form>
  <form className="incidentForm compactForm" onSubmit={createProtocolTemplate}><h2>Modelo por COBRADE</h2><label>Código do modelo<input name="code" required placeholder="PROTO-COBRADE"/></label><label>COBRADE<input name="cobradeCode" required placeholder="Informe o código oficial"/></label><label>Título<input name="title" required/></label><label>Categoria<input name="category" defaultValue="MONITORING"/></label><label>Severidade<select name="severity"><option value="">Não definida</option><option value="INFO">Informativo</option><option value="WATCH">Atenção</option><option value="WARNING">Alerta</option><option value="EMERGENCY">Emergência</option></select></label><label>Gatilho<textarea name="triggerSummary"/></label><label>Orientação<textarea name="guidance"/></label><label>Passos — um por linha<textarea name="steps"/></label><button className="primaryButton" disabled={busy}>Salvar modelo COBRADE</button></form>
  <form className="incidentForm compactForm" onSubmit={createConnector}><h2>Novo conector</h2><label>Estação<select name="stationId" required><option value="">Selecione</option>{stations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Fornecedor/código<input name="providerCode" required placeholder="GEOPIXEL, CEMADEN, MANUAL..."/></label><label>Nome de exibição<input name="displayName" required/></label><label>Modo<select name="mode" defaultValue="WEBHOOK"><option value="WEBHOOK">Webhook/entrada</option><option value="MANUAL">Manual</option></select></label><label>Referência externa<input name="externalReference" placeholder="ID da estação no fornecedor"/></label><button className="primaryButton" disabled={busy||stations.length===0}>Registrar conector</button><small>Credenciais não são gravadas aqui; use chaves de ingestão para segredos.</small></form>
  <form className="incidentForm compactForm" onSubmit={importCobrade}><h2>Importar catálogo COBRADE</h2><label>Fonte<input name="sourceName" placeholder="Ex.: catálogo oficial"/></label><label>Versão/data da fonte<input name="sourceVersion" placeholder="Ex.: 2026-09"/></label><label>CSV<textarea name="csv" required placeholder={"codigo;nome;grupo;subgrupo;tipo;subtipo\n..."} /></label><button className="primaryButton" disabled={busy}>Importar / atualizar catálogo</button><small>A importação atualiza códigos existentes e registra fonte, versão, usuário e data.</small></form>
 </section>
 <section style={{marginTop:18}}><h2>Catálogo COBRADE importado</h2><div className="dataGrid">{cobradeCatalog.length===0?<div className="infoCard">Nenhum catálogo foi importado. Enquanto estiver vazio, o SIGDEC permite informar códigos manualmente nos modelos.</div>:cobradeCatalog.slice(0,60).map(x=><article className="card" key={x.code}><h2>{x.code}</h2><p><strong>{x.name}</strong></p><p>{[x.group,x.subgroup,x.type,x.subtype].filter(Boolean).join(" · ")}</p>{(x.sourceName||x.sourceVersion)&&<small>{x.sourceName??"Fonte"}{x.sourceVersion?` · ${x.sourceVersion}`:""}</small>}</article>)}</div></section>
 <section style={{marginTop:18}}><h2>Modelos COBRADE</h2><div className="dataGrid">{protocolTemplates.length===0?<div className="infoCard">Nenhum modelo COBRADE cadastrado.</div>:protocolTemplates.map(x=><article className="card" key={x.id}><h2>{x.cobradeCode} · {x.title}</h2><p><strong>{x.code}</strong> · {x.category}{x.severity?` · ${x.severity}`:""}</p>{x.triggerSummary&&<p>{x.triggerSummary}</p>}{x.steps?.length>0&&<ol>{x.steps.map((s,i)=><li key={i}>{s}</li>)}</ol>}<button type="button" className="primaryButton" disabled={busy} onClick={()=>instantiateTemplate(x.id)}>Criar protocolo a partir deste modelo</button></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Conectores de monitoramento</h2><div className="dataGrid">{connectors.length===0?<div className="infoCard">Nenhum conector registrado.</div>:connectors.map(x=><article className="card" key={x.id}><h2>{x.displayName}</h2><p><strong>{x.providerCode}</strong> · {x.mode} · {x.status}</p><p>{x.stationCode} · {x.stationName}{x.externalReference?` · ref. ${x.externalReference}`:""}</p>{x.lastError&&<p>Último erro: {x.lastError}</p>}<div className="headerActions">{x.status!=="ACTIVE"&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>changeConnectorStatus(x.id,"ACTIVE")}>Ativar</button>}{x.status==="ACTIVE"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeConnectorStatus(x.id,"PAUSED")}>Pausar</button>}{x.status!=="DISABLED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeConnectorStatus(x.id,"DISABLED")}>Desabilitar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Governança das chaves</h2><div className="incidentForm compactForm"><label>Estação<select value={selectedKeyStation} onChange={e=>setSelectedKeyStation(e.target.value)}><option value="">Selecione</option>{stations.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label></div><div className="dataGrid">{selectedKeyStation&&keys.length===0?<div className="infoCard">Nenhuma chave cadastrada para esta estação.</div>:keys.map(x=><article className="card" key={x.id}><h2>{x.name}</h2><p><strong>{x.active?"ATIVA":"REVOGADA"}</strong></p><p>Criada em {new Date(x.createdAt).toLocaleString("pt-BR")}{x.lastUsedAt?` · último uso ${new Date(x.lastUsedAt).toLocaleString("pt-BR")}`:""}</p>{x.revokedAt&&<p>Revogada em {new Date(x.revokedAt).toLocaleString("pt-BR")}</p>}<div className="headerActions">{x.active&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>rotateKey(x.id)}>Rotacionar</button>}{x.active&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>revokeKey(x.id)}>Revogar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Protocolos operacionais</h2><div className="dataGrid">{protocols.length===0?<div className="infoCard">Nenhum protocolo cadastrado.</div>:protocols.map(x=><article className="card" key={x.id}><h2>{x.code} · {x.title}</h2><p>{x.category} · {x.activeVersionNo?`versão ativa ${x.activeVersionNo}`:"sem versão ativa"}</p>{x.guidance&&<p>{x.guidance}</p>}<button type="button" className="secondaryLink" onClick={()=>setSelectedProtocolId(x.id)}>Ver versões</button></article>)}</div>{selectedProtocolId&&<div className="dataGrid" style={{marginTop:12}}>{versions.map(v=><article className="card" key={v.id}><h2>Versão {v.versionNo}</h2><p><strong>{v.status}</strong>{v.severity?` · ${v.severity}`:""}</p>{v.triggerSummary&&<p>{v.triggerSummary}</p>}{v.steps?.length>0&&<ol>{v.steps.map((s,i)=><li key={i}>{s}</li>)}</ol>}{v.status!=="ACTIVE"&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>activateVersion(selectedProtocolId,v.id)}>Ativar esta versão</button>}</article>)}</div>}</section>
 <section style={{marginTop:18}}><h2>Eventos operacionais</h2><div className="dataGrid">{events.length===0?<div className="infoCard">Nenhum evento gerado pelos limiares.</div>:events.slice(0,24).map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.severity}</strong> · {x.status} · {x.stationCode} · {x.stationName}</p><p>{x.metric}: <strong>{x.observedValue} {x.unit}</strong> · limiar {x.thresholdValue} {x.unit}</p>{x.protocolCode&&<p><strong>Protocolo:</strong> {x.protocolCode} · v{x.protocolVersionNo}</p>}{x.protocolSteps?.length?<ol>{x.protocolSteps.map((s,i)=><li key={i}>{s}</li>)}</ol>:null}{x.guidance&&<p>{x.guidance}</p>}<div className="headerActions">{!x.alertId&&<button type="button" className="primaryButton" disabled={busy} onClick={()=>createAlertDraft(x.id)}>Criar rascunho de alerta</button>}{x.alertId&&<Link className="secondaryLink" href="/gestao">Alerta {x.alertStatus??"DRAFT"} criado</Link>}{x.status==="OPEN"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeEvent(x.id,"ACKNOWLEDGED")}>Reconhecer</button>}{x.status!=="CLOSED"&&<button type="button" className="secondaryLink" disabled={busy} onClick={()=>changeEvent(x.id,"CLOSED")}>Encerrar</button>}</div></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Últimas leituras</h2><div className="dataGrid">{readings.length===0?<div className="infoCard">Nenhuma leitura registrada.</div>:readings.map(x=><article className="card" key={`${x.stationId}-${x.metric}`}><h2>{x.stationName}</h2><p><strong>{x.metric}</strong> · {x.value} {x.unit}</p><p>{new Date(x.measuredAt).toLocaleString("pt-BR")} · {x.source}</p></article>)}</div></section>
 <section style={{marginTop:18}}><h2>Limiares configurados</h2><div className="dataGrid">{thresholds.length===0?<div className="infoCard">Nenhum limiar configurado.</div>:thresholds.map(x=><article className="card" key={x.id}><h2>{x.title}</h2><p><strong>{x.severity}</strong> · {x.stationName}</p><p>{x.metric} {x.comparison==="GTE"?"≥":"≤"} {x.thresholdValue} {x.unit}</p>{x.protocolCode&&<p>Protocolo {x.protocolCode} · v{x.protocolVersionNo}</p>}{x.guidance&&<p>{x.guidance}</p>}</article>)}</div></section>
 <section style={{marginTop:18}}><h2>Estações</h2><div className="dataGrid">{stations.length===0&&!status?<div className="infoCard">Nenhuma estação cadastrada.</div>:stations.map(x=><article className="card" key={x.id}><h2>{x.name}</h2><p><strong>{x.code}</strong> · {x.stationType}</p><p>{x.provider??"Fonte não informada"}{x.externalId?` · ID ${x.externalId}`:""}</p></article>)}</div></section>
 </main>
}