import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authFrom, requirePermission } from "../auth.js";
import { db } from "../db.js";
function org(id:string|null){if(!id)throw Object.assign(new Error("Usuário sem organização vinculada."),{statusCode:409});return id;}
const communication=z.object({incidentId:z.string().uuid().optional(),channel:z.string().trim().max(100).optional(),sender:z.string().trim().max(150).optional(),recipient:z.string().trim().max(150).optional(),message:z.string().trim().min(1).max(5000),priority:z.enum(["ROUTINE","PRIORITY","EMERGENCY"]).default("ROUTINE")});
const operation=z.object({incidentId:z.string().uuid().optional(),name:z.string().trim().min(3).max(200),commandPost:z.string().trim().max(300).optional(),objectives:z.string().trim().max(5000).optional()});
const document=z.object({incidentId:z.string().uuid().optional(),inspectionId:z.string().uuid().optional(),documentType:z.enum(["REPORT","OPINION","INTERDICTION","DECLARATION","FORM","OTHER"]),number:z.string().trim().max(80).optional(),title:z.string().trim().min(3).max(300),content:z.record(z.string(),z.unknown()).default({})});

const period=z.object({startsAt:z.coerce.date(),endsAt:z.coerce.date().optional(),objectives:z.string().trim().max(5000).optional(),situationSummary:z.string().trim().max(8000).optional()});
const asset=z.object({assetType:z.enum(["BASE_RADIO","HANDHELD_RADIO","MOBILE_RADIO","REPEATER","OTHER"]),code:z.string().trim().min(1).max(80),description:z.string().trim().min(2).max(300),channel:z.string().trim().max(100).optional(),notes:z.string().trim().max(2000).optional()});
const assignment=z.object({assignedToUserId:z.string().uuid().optional(),assignedToName:z.string().trim().min(2).max(200).optional(),notes:z.string().trim().max(2000).optional()}).refine(v=>!!v.assignedToUserId||!!v.assignedToName,{message:"Informe o responsável pela cautela."});

export async function commandRoutes(app:FastifyInstance){
 app.get("/api/v1/sco/sitrep",{preHandler:requirePermission("sco.read")},async req=>{
  const o=org(authFrom(req).organizationId);
  const r=await db.query(`SELECT
   (SELECT count(*) FROM incidents WHERE organization_id=$1 AND status NOT IN ('CLOSED','CANCELLED','DUPLICATE'))::int AS "activeIncidents",
   (SELECT count(*) FROM incidents WHERE organization_id=$1 AND status NOT IN ('CLOSED','CANCELLED','DUPLICATE') AND priority='P1')::int AS "p1Incidents",
   (SELECT count(*) FROM incidents WHERE organization_id=$1 AND status NOT IN ('CLOSED','CANCELLED','DUPLICATE') AND priority='P2')::int AS "p2Incidents",
   (SELECT count(*) FROM monitoring_events WHERE organization_id=$1 AND status<>'CLOSED')::int AS "openMonitoringEvents",
   (SELECT count(*) FROM monitoring_events WHERE organization_id=$1 AND status<>'CLOSED' AND severity='EMERGENCY')::int AS "emergencyMonitoringEvents",
   (SELECT count(*) FROM alerts WHERE organization_id=$1 AND status='PUBLISHED')::int AS "publishedAlerts",
   (SELECT count(*) FROM shelters WHERE organization_id=$1 AND status IN ('OPEN','FULL'))::int AS "openShelters",
   (SELECT count(*) FROM assisted_households WHERE organization_id=$1 AND departed_at IS NULL AND condition='DISPLACED')::int AS "displacedHouseholds",
   (SELECT count(*) FROM assisted_households WHERE organization_id=$1 AND departed_at IS NULL AND condition='HOMELESS')::int AS "homelessHouseholds",
   (SELECT count(*) FROM emergency_operations WHERE organization_id=$1 AND ended_at IS NULL)::int AS "activeOperations",
   (SELECT count(*) FROM operational_periods p JOIN emergency_operations e ON e.id=p.operation_id WHERE e.organization_id=$1 AND p.status='ACTIVE')::int AS "activeOperationalPeriods"`,[o]);
  return {generatedAt:new Date().toISOString(),...r.rows[0]};
 });
 app.get("/api/v1/communications",{preHandler:requirePermission("communications.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT c.id,c.occurred_at AS "occurredAt",c.channel,c.sender,c.recipient,c.message,c.priority,i.protocol FROM operational_communications c LEFT JOIN incidents i ON i.id=c.incident_id WHERE c.organization_id=$1 ORDER BY c.occurred_at DESC LIMIT 300`,[o]);return {items:r.rows};});
 app.post("/api/v1/communications",{preHandler:requirePermission("communications.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=communication.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO operational_communications(organization_id,incident_id,recorded_by,channel,sender,recipient,message,priority) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[o,v.incidentId??null,a.userId,v.channel??null,v.sender??null,v.recipient??null,v.message,v.priority]);return reply.code(201).send({id:r.rows[0]?.id});});
 app.get("/api/v1/sco/operations",{preHandler:requirePermission("sco.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT e.id,e.name,e.status,e.command_post AS "commandPost",e.objectives,e.started_at AS "startedAt",e.ended_at AS "endedAt",i.protocol FROM emergency_operations e LEFT JOIN incidents i ON i.id=e.incident_id WHERE e.organization_id=$1 ORDER BY e.started_at DESC`,[o]);return {items:r.rows};});
 app.post("/api/v1/sco/operations",{preHandler:requirePermission("sco.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=operation.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO emergency_operations(organization_id,incident_id,name,command_post,commander_user_id,objectives,created_by) VALUES($1,$2,$3,$4,$5,$6,$5) RETURNING id`,[o,v.incidentId??null,v.name,v.commandPost??null,a.userId,v.objectives??null]);return reply.code(201).send({id:r.rows[0]?.id});});
 app.get("/api/v1/documents",{preHandler:requirePermission("documents.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT d.id,d.document_type AS "documentType",d.number,d.title,d.status,d.created_at AS "createdAt",d.issued_at AS "issuedAt",i.protocol FROM technical_documents d LEFT JOIN incidents i ON i.id=d.incident_id WHERE d.organization_id=$1 ORDER BY d.created_at DESC`,[o]);return {items:r.rows};});
 app.post("/api/v1/documents",{preHandler:requirePermission("documents.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=document.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO technical_documents(organization_id,incident_id,inspection_id,document_type,number,title,content,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[o,v.incidentId??null,v.inspectionId??null,v.documentType,v.number??null,v.title,JSON.stringify(v.content),a.userId]);return reply.code(201).send({id:r.rows[0]?.id});});
 app.get("/api/v1/communications/assets",{preHandler:requirePermission("communications.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT a.id,a.asset_type AS "assetType",a.code,a.description,a.channel,a.status,a.notes,ca.assigned_to_name AS "assignedToName",ca.assigned_at AS "assignedAt" FROM communication_assets a LEFT JOIN LATERAL (SELECT assigned_to_name,assigned_at FROM communication_assignments x WHERE x.asset_id=a.id AND x.returned_at IS NULL ORDER BY assigned_at DESC LIMIT 1) ca ON true WHERE a.organization_id=$1 ORDER BY a.code`,[o]);return {items:r.rows};});
 app.post("/api/v1/communications/assets",{preHandler:requirePermission("communications.manage")},async(req,reply)=>{const o=org(authFrom(req).organizationId),p=asset.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO communication_assets(organization_id,asset_type,code,description,channel,notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[o,v.assetType,v.code,v.description,v.channel??null,v.notes??null]);return reply.code(201).send({id:r.rows[0]?.id});});
 app.post("/api/v1/communications/assets/:id/assign",{preHandler:requirePermission("communications.assign")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),{id}=req.params as {id:string},p=assignment.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const exists=await db.query("SELECT 1 FROM communication_assets WHERE id=$1 AND organization_id=$2",[id,o]);if(!exists.rows[0])return reply.code(404).send({error:"NOT_FOUND"});const open=await db.query("SELECT 1 FROM communication_assignments WHERE asset_id=$1 AND returned_at IS NULL",[id]);if(open.rows[0])return reply.code(409).send({error:"ALREADY_ASSIGNED"});const v=p.data;await db.query("BEGIN");try{await db.query(`INSERT INTO communication_assignments(organization_id,asset_id,assigned_to_user_id,assigned_to_name,notes,created_by) VALUES($1,$2,$3,$4,$5,$6)`,[o,id,v.assignedToUserId??null,v.assignedToName??null,v.notes??null,a.userId]);await db.query("UPDATE communication_assets SET status='ASSIGNED' WHERE id=$1",[id]);await db.query("COMMIT");}catch(e){await db.query("ROLLBACK");throw e}return reply.code(201).send({ok:true});});
 app.post("/api/v1/communications/assets/:id/return",{preHandler:requirePermission("communications.assign")},async(req,reply)=>{const o=org(authFrom(req).organizationId),{id}=req.params as {id:string};const exists=await db.query("SELECT 1 FROM communication_assets WHERE id=$1 AND organization_id=$2",[id,o]);if(!exists.rows[0])return reply.code(404).send({error:"NOT_FOUND"});await db.query("BEGIN");try{const r=await db.query("UPDATE communication_assignments SET returned_at=now() WHERE asset_id=$1 AND returned_at IS NULL RETURNING id",[id]);if(!r.rows[0]){await db.query("ROLLBACK");return reply.code(409).send({error:"NOT_ASSIGNED"});}await db.query("UPDATE communication_assets SET status='AVAILABLE' WHERE id=$1",[id]);await db.query("COMMIT");}catch(e){await db.query("ROLLBACK");throw e}return {ok:true};});
 app.get("/api/v1/sco/operations/:id/periods",{preHandler:requirePermission("sco.read")},async(req,reply)=>{const o=org(authFrom(req).organizationId),{id}=req.params as {id:string};const op=await db.query("SELECT 1 FROM emergency_operations WHERE id=$1 AND organization_id=$2",[id,o]);if(!op.rows[0])return reply.code(404).send({error:"NOT_FOUND"});const r=await db.query(`SELECT id,sequence_no AS "sequenceNo",starts_at AS "startsAt",ends_at AS "endsAt",objectives,situation_summary AS "situationSummary",status,approved_at AS "approvedAt" FROM operational_periods WHERE operation_id=$1 ORDER BY sequence_no`,[id]);return {items:r.rows};});
 app.post("/api/v1/sco/operations/:id/periods",{preHandler:requirePermission("sco.periods.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),{id}=req.params as {id:string},p=period.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const op=await db.query("SELECT 1 FROM emergency_operations WHERE id=$1 AND organization_id=$2",[id,o]);if(!op.rows[0])return reply.code(404).send({error:"NOT_FOUND"});const v=p.data,r=await db.query(`INSERT INTO operational_periods(operation_id,sequence_no,starts_at,ends_at,objectives,situation_summary,created_by) SELECT $1,COALESCE(MAX(sequence_no),0)+1,$2,$3,$4,$5,$6 FROM operational_periods WHERE operation_id=$1 RETURNING id,sequence_no AS "sequenceNo"`,[id,v.startsAt,v.endsAt??null,v.objectives??null,v.situationSummary??null,a.userId]);return reply.code(201).send(r.rows[0]);});
 app.post("/api/v1/documents/:id/issue",{preHandler:requirePermission("documents.issue")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),{id}=req.params as {id:string};await db.query("BEGIN");try{const d=await db.query("SELECT content,status FROM technical_documents WHERE id=$1 AND organization_id=$2 FOR UPDATE",[id,o]);if(!d.rows[0]){await db.query("ROLLBACK");return reply.code(404).send({error:"NOT_FOUND"});}if(d.rows[0].status==='CANCELLED'){await db.query("ROLLBACK");return reply.code(409).send({error:"CANCELLED"});}const v=await db.query(`INSERT INTO technical_document_versions(document_id,version_no,content,change_summary,created_by) SELECT $1,COALESCE(MAX(version_no),0)+1,$2,'Emissão do documento',$3 FROM technical_document_versions WHERE document_id=$1 RETURNING version_no AS "versionNo"`,[id,d.rows[0].content,a.userId]);await db.query("UPDATE technical_documents SET status='ISSUED',issued_at=now() WHERE id=$1",[id]);await db.query("COMMIT");return {ok:true,versionNo:v.rows[0]?.versionNo};}catch(e){await db.query("ROLLBACK");throw e}});

}