import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authFrom, requirePermission } from "../auth.js";
import { db } from "../db.js";
function org(id:string|null){if(!id)throw Object.assign(new Error("Usuário sem organização vinculada."),{statusCode:409});return id;}
const communication=z.object({incidentId:z.string().uuid().optional(),channel:z.string().trim().max(100).optional(),sender:z.string().trim().max(150).optional(),recipient:z.string().trim().max(150).optional(),message:z.string().trim().min(1).max(5000),priority:z.enum(["ROUTINE","PRIORITY","EMERGENCY"]).default("ROUTINE")});
const operation=z.object({incidentId:z.string().uuid().optional(),name:z.string().trim().min(3).max(200),commandPost:z.string().trim().max(300).optional(),objectives:z.string().trim().max(5000).optional()});
const document=z.object({incidentId:z.string().uuid().optional(),inspectionId:z.string().uuid().optional(),documentType:z.enum(["REPORT","OPINION","INTERDICTION","DECLARATION","FORM","OTHER"]),number:z.string().trim().max(80).optional(),title:z.string().trim().min(3).max(300),content:z.record(z.string(),z.unknown()).default({})});
export async function commandRoutes(app:FastifyInstance){
 app.get("/api/v1/communications",{preHandler:requirePermission("communications.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT c.id,c.occurred_at AS "occurredAt",c.channel,c.sender,c.recipient,c.message,c.priority,i.protocol FROM operational_communications c LEFT JOIN incidents i ON i.id=c.incident_id WHERE c.organization_id=$1 ORDER BY c.occurred_at DESC LIMIT 300`,[o]);return {items:r.rows};});
 app.post("/api/v1/communications",{preHandler:requirePermission("communications.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=communication.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO operational_communications(organization_id,incident_id,recorded_by,channel,sender,recipient,message,priority) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[o,v.incidentId??null,a.userId,v.channel??null,v.sender??null,v.recipient??null,v.message,v.priority]);return reply.code(201).send({id:r.rows[0]?.id});});
 app.get("/api/v1/sco/operations",{preHandler:requirePermission("sco.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT e.id,e.name,e.status,e.command_post AS "commandPost",e.objectives,e.started_at AS "startedAt",e.ended_at AS "endedAt",i.protocol FROM emergency_operations e LEFT JOIN incidents i ON i.id=e.incident_id WHERE e.organization_id=$1 ORDER BY e.started_at DESC`,[o]);return {items:r.rows};});
 app.post("/api/v1/sco/operations",{preHandler:requirePermission("sco.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=operation.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO emergency_operations(organization_id,incident_id,name,command_post,commander_user_id,objectives,created_by) VALUES($1,$2,$3,$4,$5,$6,$5) RETURNING id`,[o,v.incidentId??null,v.name,v.commandPost??null,a.userId,v.objectives??null]);return reply.code(201).send({id:r.rows[0]?.id});});
 app.get("/api/v1/documents",{preHandler:requirePermission("documents.read")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query(`SELECT d.id,d.document_type AS "documentType",d.number,d.title,d.status,d.created_at AS "createdAt",d.issued_at AS "issuedAt",i.protocol FROM technical_documents d LEFT JOIN incidents i ON i.id=d.incident_id WHERE d.organization_id=$1 ORDER BY d.created_at DESC`,[o]);return {items:r.rows};});
 app.post("/api/v1/documents",{preHandler:requirePermission("documents.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=document.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query(`INSERT INTO technical_documents(organization_id,incident_id,inspection_id,document_type,number,title,content,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[o,v.incidentId??null,v.inspectionId??null,v.documentType,v.number??null,v.title,JSON.stringify(v.content),a.userId]);return reply.code(201).send({id:r.rows[0]?.id});});
}