import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authFrom, requirePermission } from "../auth.js";
import { db } from "../db.js";
function org(id:string|null){if(!id)throw Object.assign(new Error("Usuário sem organização vinculada."),{statusCode:409});return id;}
const risk=z.object({code:z.string().trim().min(1).max(40),title:z.string().trim().min(3).max(240),category:z.string().trim().min(2).max(100),probability:z.number().int().min(1).max(5),impact:z.number().int().min(1).max(5),mitigation:z.string().trim().max(5000).optional()});
const alert=z.object({riskId:z.string().uuid().optional(),severity:z.enum(["INFO","WATCH","WARNING","EMERGENCY"]),title:z.string().trim().min(3).max(240),message:z.string().trim().min(3).max(5000)});
const s2id=z.object({incidentId:z.string().uuid().optional(),cobrade:z.string().trim().min(3).max(30),recordType:z.enum(["FIDE","DMATE","OTHER"]),payload:z.record(z.string(),z.unknown()).default({})});
const training=z.object({name:z.string().trim().min(3).max(240),trainingType:z.enum(["COURSE","DRILL","SIMULATION","AAR"]),startsAt:z.coerce.date(),endsAt:z.coerce.date().optional(),location:z.string().trim().max(240).optional(),objectives:z.string().trim().max(5000).optional()});
const recovery=z.object({incidentId:z.string().uuid().optional(),title:z.string().trim().min(3).max(240),category:z.string().trim().min(2).max(100),responsible:z.string().trim().max(200).optional(),estimatedCost:z.number().nonnegative().optional(),notes:z.string().trim().max(5000).optional()});
export async function planningRoutes(app:FastifyInstance){
 app.get("/api/v1/management/summary",{preHandler:requirePermission("bi.read")},async req=>{const o=org(authFrom(req).organizationId);const r=await db.query(`SELECT
 (SELECT count(*) FROM risk_registers WHERE organization_id=$1 AND status='ACTIVE')::int AS "activeRisks",
 (SELECT count(*) FROM alerts WHERE organization_id=$1 AND status<>'CLOSED')::int AS "openAlerts",
 (SELECT count(*) FROM s2id_records WHERE organization_id=$1)::int AS "s2idRecords",
 (SELECT count(*) FROM trainings WHERE organization_id=$1)::int AS trainings,
 (SELECT count(*) FROM recovery_actions WHERE organization_id=$1 AND status<>'DONE')::int AS "recoveryActions"`,[o]);return r.rows[0];});
 app.get("/api/v1/risks",{preHandler:requirePermission("risks.manage")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query('SELECT id,code,title,category,probability,impact,status,mitigation,created_at AS "createdAt" FROM risk_registers WHERE organization_id=$1 ORDER BY probability*impact DESC,created_at DESC',[o]);return {items:r.rows};});
 app.post("/api/v1/risks",{preHandler:requirePermission("risks.manage")},async(req,reply)=>{const o=org(authFrom(req).organizationId),p=risk.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query('INSERT INTO risk_registers(organization_id,code,title,category,probability,impact,mitigation) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[o,v.code,v.title,v.category,v.probability,v.impact,v.mitigation??null]);return reply.code(201).send(r.rows[0]);});
 app.get("/api/v1/alerts",{preHandler:requirePermission("alerts.manage")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query('SELECT id,severity,title,message,status,starts_at AS "startsAt",ends_at AS "endsAt",created_at AS "createdAt" FROM alerts WHERE organization_id=$1 ORDER BY created_at DESC LIMIT 200',[o]);return {items:r.rows};});
 app.post("/api/v1/alerts",{preHandler:requirePermission("alerts.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=alert.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query('INSERT INTO alerts(organization_id,risk_id,severity,title,message,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[o,v.riskId??null,v.severity,v.title,v.message,a.userId]);return reply.code(201).send(r.rows[0]);});
 app.get("/api/v1/s2id",{preHandler:requirePermission("s2id.manage")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query('SELECT id,cobrade,record_type AS "recordType",status,created_at AS "createdAt" FROM s2id_records WHERE organization_id=$1 ORDER BY created_at DESC',[o]);return {items:r.rows};});
 app.post("/api/v1/s2id",{preHandler:requirePermission("s2id.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=s2id.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query('INSERT INTO s2id_records(organization_id,incident_id,cobrade,record_type,payload,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id',[o,v.incidentId??null,v.cobrade,v.recordType,JSON.stringify(v.payload),a.userId]);return reply.code(201).send(r.rows[0]);});
 app.get("/api/v1/trainings",{preHandler:requirePermission("training.manage")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query('SELECT id,name,training_type AS "trainingType",starts_at AS "startsAt",ends_at AS "endsAt",location,objectives FROM trainings WHERE organization_id=$1 ORDER BY starts_at DESC',[o]);return {items:r.rows};});
 app.post("/api/v1/trainings",{preHandler:requirePermission("training.manage")},async(req,reply)=>{const a=authFrom(req),o=org(a.organizationId),p=training.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query('INSERT INTO trainings(organization_id,name,training_type,starts_at,ends_at,location,objectives,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[o,v.name,v.trainingType,v.startsAt,v.endsAt??null,v.location??null,v.objectives??null,a.userId]);return reply.code(201).send(r.rows[0]);});
 app.get("/api/v1/recovery",{preHandler:requirePermission("recovery.manage")},async req=>{const o=org(authFrom(req).organizationId),r=await db.query('SELECT id,title,category,status,estimated_cost AS "estimatedCost",responsible,due_at AS "dueAt",notes FROM recovery_actions WHERE organization_id=$1 ORDER BY created_at DESC',[o]);return {items:r.rows};});
 app.post("/api/v1/recovery",{preHandler:requirePermission("recovery.manage")},async(req,reply)=>{const o=org(authFrom(req).organizationId),p=recovery.safeParse(req.body);if(!p.success)return reply.code(400).send({error:"INVALID_INPUT",details:p.error.flatten()});const v=p.data,r=await db.query('INSERT INTO recovery_actions(organization_id,incident_id,title,category,estimated_cost,responsible,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[o,v.incidentId??null,v.title,v.category,v.estimatedCost??null,v.responsible??null,v.notes??null]);return reply.code(201).send(r.rows[0]);});
}