"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../../lib/release";
import {formatDateTimeBR} from "../../lib/datetime";
import {useRealtimeRefresh} from "../../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
const itemPt:Record<string,string>={OBJECTIVE:"Objetivo",ASSIGNMENT:"Atribuição",SAFETY:"Segurança",MEDICAL:"Plano médico",COMMUNICATION:"Comunicações",LOGISTICS:"Logística",DEMOBILIZATION:"Desmobilização"};
export default function Page(){
 const[operations,setOperations]=useState<Row[]>([]),[operationId,setOperationId]=useState(""),[periods,setPeriods]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const loadOperations=useCallback(async()=>{try{const b=await request("/api/v1/sco/operations");setOperations(b.items??[]);setOperationId(current=>current||b.items?.[0]?.id||"");setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar operações.")}},[request]);
 const loadDetail=useCallback(async(id:string)=>{if(!id){setPeriods([]);setItems([]);return}try{const[p,a]=await Promise.all([request("/api/v1/sco/operations/"+id+"/periods"),request("/api/v1/sco/operations/"+id+"/action-plan")]);setPeriods(p.items??[]);setItems(a.items??[])}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar PAI.")}},[request]);
 useEffect(()=>{void loadOperations()},[loadOperations]);useEffect(()=>{void loadDetail(operationId)},[operationId,loadDetail]);useRealtimeRefresh(async()=>{if(busy)return;await loadOperations();if(operationId)await loadDetail(operationId)},true,5000);
 async function perform(fn:()=>Promise<void>){setBusy(true);setMsg("");try{await fn();await loadOperations();if(operationId)await loadDetail(operationId)}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 async function createPeriod(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!operationId)return;const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/sco/operations/"+operationId+"/periods",{method:"POST",body:JSON.stringify({startsAt:String(d.get("startsAt")),endsAt:String(d.get("endsAt")||"")||undefined,objectives:String(d.get("objectives")||"")||undefined,situationSummary:String(d.get("situationSummary")||"")||undefined})});f.reset();setMsg("Período operacional criado.")})}
 async function createItem(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!operationId)return;const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/sco/operations/"+operationId+"/action-plan",{method:"POST",body:JSON.stringify({periodId:String(d.get("periodId")||"")||undefined,itemType:String(d.get("itemType")),title:String(d.get("title")),detail:String(d.get("detail")||"")||undefined,dueAt:String(d.get("dueAt")||"")||undefined})});f.reset();setMsg("Item do Plano de Ação registrado.")})}
 async function changeStatus(id:string,status:string){await perform(()=>request("/api/v1/sco/action-plan/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})}))}
 const selected=operations.find(x=>x.id===operationId);
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · SCO · PLANO DE AÇÃO · {SIGDEC_VERSION_LABEL}</span><h1>Plano de Ação do Incidente — PAI</h1><p>Períodos operacionais, objetivos, atribuições, segurança, comunicações, logística, plano médico e desmobilização.</p></div><div className="headerActions"><Link className="secondaryLink" href="/sco">SCO</Link><Link className="secondaryLink" href="/campo?monitor=1">Sala de Situação</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="incidentForm compactForm"><label>Operação SCO<select value={operationId} onChange={e=>setOperationId(e.target.value)}><option value="">Selecione</option>{operations.map(x=><option key={x.id} value={x.id}>{x.name}{x.protocol?" · "+x.protocol:""}</option>)}</select></label>{selected&&<p><strong>{selected.name}</strong> · {selected.status} · {selected.commandPost??"Posto de comando não informado"}</p>}</section>
  {operationId&&<><section className="operationsGrid" style={{marginTop:18}}>
   <form className="incidentForm compactForm" onSubmit={createPeriod}><h2>Novo período operacional</h2><label>Início<input name="startsAt" type="datetime-local" required/></label><label>Fim previsto<input name="endsAt" type="datetime-local"/></label><label>Objetivos<textarea name="objectives"/></label><label>Situação / briefing<textarea name="situationSummary"/></label><button className="primaryButton" disabled={busy}>Criar período</button></form>
   <form className="incidentForm compactForm" onSubmit={createItem}><h2>Novo item do PAI</h2><label>Período<select name="periodId"><option value="">Sem período específico</option>{periods.map(x=><option key={x.id} value={x.id}>Período {x.sequenceNo} · {formatDateTimeBR(x.startsAt)}</option>)}</select></label><label>Tipo<select name="itemType">{Object.entries(itemPt).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Título<input name="title" required/></label><label>Detalhamento<textarea name="detail"/></label><label>Prazo<input name="dueAt" type="datetime-local"/></label><button className="primaryButton" disabled={busy}>Adicionar ao PAI</button></form>
  </section>
  <section style={{marginTop:22}}><h2>Períodos operacionais</h2><div className="dataGrid">{periods.map(x=><article className="card" key={x.id}><h3>Período {x.sequenceNo}</h3><p><strong>{x.status}</strong> · {formatDateTimeBR(x.startsAt)}{x.endsAt?" → "+formatDateTimeBR(x.endsAt):""}</p><p>{x.objectives??"Sem objetivos registrados"}</p>{x.situationSummary&&<p><strong>Situação:</strong> {x.situationSummary}</p>}</article>)}</div></section>
  <section style={{marginTop:22}}><h2>Plano de Ação</h2><div className="dataGrid">{items.map(x=><article className={x.itemType==="SAFETY"&&x.status!=="DONE"?"warningCard":"card"} key={x.id}><h3>{itemPt[x.itemType]??x.itemType} · {x.title}</h3><p><strong>{x.status}</strong>{x.periodSequence?" · período "+x.periodSequence:""}</p>{x.detail&&<p>{x.detail}</p>}<p>{x.teamCode?"Equipe "+x.teamCode:""}{x.assignedUserName?" · "+x.assignedUserName:""}{x.dueAt?" · prazo "+formatDateTimeBR(x.dueAt):""}</p><div className="headerActions">{x.status==="OPEN"&&<button className="secondaryButton" onClick={()=>void changeStatus(x.id,"IN_PROGRESS")}>Iniciar</button>}{!["DONE","CANCELLED"].includes(x.status)&&<button className="primaryButton" onClick={()=>void changeStatus(x.id,"DONE")}>Concluir</button>}</div></article>)}</div></section>
  </>}
 </main>
}
