"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../lib/release";
import {formatDateTimeBR} from "../lib/datetime";
import {useRealtimeRefresh} from "../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
const catPt:Record<string,string>={WATER:"Água",ENERGY:"Energia",TELECOM:"Telecom",HEALTH:"Saúde",EDUCATION:"Educação",ROAD:"Via",BRIDGE:"Ponte",DRAINAGE:"Drenagem",FUEL:"Combustível",PUBLIC_SAFETY:"Segurança pública",SHELTER:"Abrigo",OTHER:"Outro"};
const statusPt:Record<string,string>={OPERATIONAL:"Operacional",DEGRADED:"Degradado",INTERRUPTED:"Interrompido",UNKNOWN:"Desconhecido",RESTORED:"Restabelecido",READY:"Pronto",RESTRICTED:"Restrito",MAINTENANCE:"Manutenção",UNAVAILABLE:"Indisponível"};
export default function Page(){
 const[infra,setInfra]=useState<Row[]>([]),[readiness,setReadiness]=useState<Row[]>([]),[incidents,setIncidents]=useState<Row[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("infra");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[i,r,inc]=await Promise.all([request("/api/v1/critical-infrastructures"),request("/api/v1/resource-readiness"),request("/api/v1/incidents?limit=100")]);setInfra(i.items??[]);setReadiness(r.items??[]);setIncidents(inc.items??[]);setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar.")}},[request]);
 useEffect(()=>{void load()},[load]);useRealtimeRefresh(()=>{if(!busy)return load()},true,5000);
 async function perform(fn:()=>Promise<void>){setBusy(true);setMsg("");try{await fn();await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 const num=(v:FormDataEntryValue|null)=>{const s=String(v??"").trim().replace(",",".");return s?Number(s):undefined};const opt=(v:FormDataEntryValue|null)=>String(v??"").trim()||undefined;
 async function createInfra(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/critical-infrastructures",{method:"POST",body:JSON.stringify({code:String(d.get("code")),name:String(d.get("name")),category:String(d.get("category")),ownerName:opt(d.get("ownerName")),responsibleName:opt(d.get("responsibleName")),responsiblePhone:opt(d.get("responsiblePhone")),addressLine:opt(d.get("addressLine")),neighborhood:opt(d.get("neighborhood")),latitude:num(d.get("latitude")),longitude:num(d.get("longitude")),criticality:String(d.get("criticality")),redundancy:opt(d.get("redundancy")),backupPower:d.get("backupPower")==="on",autonomyHours:num(d.get("autonomyHours")),notes:opt(d.get("notes"))})});f.reset();setMsg("Infraestrutura cadastrada.")})}
 async function eventInfra(item:Row){const status=prompt("Novo status: OPERATIONAL, DEGRADED, INTERRUPTED ou RESTORED",item.operationalStatus==="OPERATIONAL"?"DEGRADED":item.operationalStatus)?.trim().toUpperCase();if(!status||!["OPERATIONAL","DEGRADED","INTERRUPTED","RESTORED"].includes(status))return;const incidentId=prompt("ID da ocorrência vinculada (opcional):","")?.trim()||undefined;const impact=prompt("Impacto operacional:","")??"";const notes=prompt("Observações:","")??"";await perform(()=>request("/api/v1/critical-infrastructures/"+item.id+"/events",{method:"POST",body:JSON.stringify({incidentId,status,impact,notes})}))}
 async function createReadiness(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/resource-readiness",{method:"POST",body:JSON.stringify({resourceType:String(d.get("resourceType")),code:String(d.get("code")),name:String(d.get("name")),readinessStatus:String(d.get("readinessStatus")),nextMaintenanceAt:opt(d.get("nextMaintenanceAt")),calibrationDueAt:opt(d.get("calibrationDueAt")),fuelLevelPercent:num(d.get("fuelLevelPercent")),batteryPercent:num(d.get("batteryPercent")),locationText:opt(d.get("locationText")),notes:opt(d.get("notes"))})});f.reset();setMsg("Prontidão do recurso atualizada.")})}
 const degraded=useMemo(()=>infra.filter(x=>x.operationalStatus!=="OPERATIONAL"),[infra]);const unavailable=useMemo(()=>readiness.filter(x=>x.readinessStatus!=="READY"),[readiness]);
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · INFRAESTRUTURAS E LOGÍSTICA · {SIGDEC_VERSION_LABEL}</span><h1>Infraestruturas Críticas e Prontidão</h1><p>Serviços essenciais, redundância, autonomia, equipamentos e disponibilidade operacional.</p></div><div className="headerActions"><Link className="secondaryLink" href="/gestao-riscos">Gestão do Risco</Link><Link className="secondaryLink" href="/campo?monitor=1">Monitor em tempo real</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="statsGrid"><article><strong>{infra.length}</strong><span>Ativos críticos cadastrados</span></article><article className={degraded.length?"warningCard":""}><strong>{degraded.length}</strong><span>Degradados/interrompidos</span></article><article><strong>{readiness.length}</strong><span>Recursos com prontidão</span></article><article className={unavailable.length?"warningCard":""}><strong>{unavailable.length}</strong><span>Recursos restritos/indisponíveis</span></article></section>
  <div className="adminTabs" style={{marginTop:18}}><button className={tab==="infra"?"active":""} onClick={()=>setTab("infra")}>Infraestruturas críticas</button><button className={tab==="readiness"?"active":""} onClick={()=>setTab("readiness")}>Prontidão logística</button></div>
  {tab==="infra"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createInfra}><h2>Novo ativo crítico</h2><div className="formGrid"><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><label>Categoria<select name="category">{Object.entries(catPt).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Criticidade<select name="criticality"><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label>Proprietário / órgão<input name="ownerName"/></label><label>Responsável<input name="responsibleName"/></label><label>Contato<input name="responsiblePhone"/></label><label>Endereço<input name="addressLine"/></label><label>Bairro<input name="neighborhood"/></label><label>Latitude<input name="latitude" type="number" step="any"/></label><label>Longitude<input name="longitude" type="number" step="any"/></label><label>Autonomia (h)<input name="autonomyHours" type="number" min="0" step="0.1"/></label><label><input name="backupPower" type="checkbox"/> Possui energia de contingência</label></div><label>Redundância / contingência<textarea name="redundancy"/></label><label>Notas<textarea name="notes"/></label><button className="primaryButton">Cadastrar infraestrutura</button></form><div className="dataGrid" style={{marginTop:18}}>{infra.map(x=><article className={x.operationalStatus==="OPERATIONAL"?"card":"warningCard"} key={x.id}><h3>{x.code} · {x.name}</h3><p><strong>{catPt[x.category]??x.category}</strong> · {x.criticality} · {statusPt[x.operationalStatus]??x.operationalStatus}</p><p>{x.neighborhood??x.addressLine??"Local não informado"}</p><p>{x.backupPower?"Possui energia de contingência":"Sem energia de contingência informada"}{x.autonomyHours!=null?" · autonomia "+x.autonomyHours+" h":""}</p><p>{x.responsibleName??"Sem responsável"}{x.responsiblePhone?" · "+x.responsiblePhone:""}</p><button className="secondaryButton" onClick={()=>void eventInfra(x)}>Registrar alteração de status</button></article>)}</div></>}
  {tab==="readiness"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createReadiness}><h2>Prontidão de recurso</h2><div className="formGrid"><label>Tipo<select name="resourceType"><option>VEHICLE</option><option>EQUIPMENT</option><option>RADIO</option><option>GENERATOR</option><option>BOAT</option><option>PUMP</option><option>OTHER</option></select></label><label>Código<input name="code" required/></label><label>Recurso<input name="name" required/></label><label>Situação<select name="readinessStatus"><option>READY</option><option>RESTRICTED</option><option>MAINTENANCE</option><option>UNAVAILABLE</option></select></label><label>Próxima manutenção<input name="nextMaintenanceAt" type="datetime-local"/></label><label>Calibração / validade<input name="calibrationDueAt" type="datetime-local"/></label><label>Combustível %<input name="fuelLevelPercent" type="number" min="0" max="100"/></label><label>Bateria %<input name="batteryPercent" type="number" min="0" max="100"/></label><label>Localização<input name="locationText"/></label></div><label>Notas<textarea name="notes"/></label><button className="primaryButton">Registrar prontidão</button></form><div className="adminTableWrap" style={{marginTop:18}}><table><thead><tr><th>Recurso</th><th>Situação</th><th>Manutenção</th><th>Calibração</th><th>Combustível/Bateria</th><th>Local</th><th>Atualização</th></tr></thead><tbody>{readiness.map(x=><tr key={x.id}><td><strong>{x.code}</strong><br/><small>{x.name} · {x.resourceType}</small></td><td>{statusPt[x.readinessStatus]??x.readinessStatus}</td><td>{x.nextMaintenanceAt?formatDateTimeBR(x.nextMaintenanceAt):"—"}</td><td>{x.calibrationDueAt?formatDateTimeBR(x.calibrationDueAt):"—"}</td><td>{x.fuelLevelPercent!=null?"Comb. "+x.fuelLevelPercent+"% ":""}{x.batteryPercent!=null?"Bat. "+x.batteryPercent+"%":""}</td><td>{x.locationText??"—"}</td><td>{formatDateTimeBR(x.updatedAt)}</td></tr>)}</tbody></table></div></>}
 </main>
}
