"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../../lib/release";
import {formatDateTimeBR} from "../../lib/datetime";
import {useRealtimeRefresh} from "../../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
const statusPt:Record<string,string>={RESCUED:"Resgatado",SHELTERED:"Abrigado",VETERINARY:"Atendimento veterinário",RETURNED:"Devolvido ao tutor",TRANSFERRED:"Transferido",DECEASED:"Óbito"};
const healthPt:Record<string,string>={UNKNOWN:"Não avaliado",STABLE:"Estável",INJURED:"Ferido",CRITICAL:"Crítico",DECEASED:"Óbito"};
export default function Page(){
 const[items,setItems]=useState<Row[]>([]),[incidents,setIncidents]=useState<Row[]>([]),[shelters,setShelters]=useState<Row[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[a,i,s]=await Promise.all([request("/api/v1/animal-rescues"),request("/api/v1/incidents?limit=100"),request("/api/v1/shelters/readiness")]);setItems(a.items??[]);setIncidents(i.items??[]);setShelters(s.items??[]);setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar.")}},[request]);
 useEffect(()=>{void load()},[load]);useRealtimeRefresh(()=>{if(!busy)return load()},true,5000);
 async function perform(fn:()=>Promise<void>){setBusy(true);setMsg("");try{await fn();await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 const num=(v:FormDataEntryValue|null)=>{const s=String(v??"").trim().replace(",",".");return s?Number(s):undefined};const opt=(v:FormDataEntryValue|null)=>String(v??"").trim()||undefined;
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/animal-rescues",{method:"POST",body:JSON.stringify({incidentId:opt(d.get("incidentId")),shelterId:opt(d.get("shelterId")),species:String(d.get("species")),quantity:Number(d.get("quantity")||1),animalName:opt(d.get("animalName")),identification:opt(d.get("identification")),tutorName:opt(d.get("tutorName")),tutorPhone:opt(d.get("tutorPhone")),foundLocation:opt(d.get("foundLocation")),latitude:num(d.get("latitude")),longitude:num(d.get("longitude")),destination:opt(d.get("destination")),healthStatus:String(d.get("healthStatus")),veterinaryNotes:opt(d.get("veterinaryNotes")),microchip:opt(d.get("microchip")),vaccinationStatus:opt(d.get("vaccinationStatus"))})});f.reset();setMsg("Resgate de animal registrado.")})}
 async function changeStatus(item:Row){const next=prompt("Novo status: RESCUED, SHELTERED, VETERINARY, RETURNED, TRANSFERRED ou DECEASED",item.status)?.trim().toUpperCase();if(!next||!Object.keys(statusPt).includes(next))return;const destination=["RETURNED","TRANSFERRED"].includes(next)?prompt("Destino / tutor / instituição:",item.destination??"")??"":undefined;await perform(()=>request("/api/v1/animal-rescues/"+item.id+"/status",{method:"PATCH",body:JSON.stringify({status:next,destination})}))}
 const active=useMemo(()=>items.filter(x=>!["RETURNED","TRANSFERRED","DECEASED"].includes(x.status)),[items]);
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · ASSISTÊNCIA HUMANITÁRIA · ANIMAIS · {SIGDEC_VERSION_LABEL}</span><h1>Animais em Desastres</h1><p>Resgate, abrigo, identificação, atendimento veterinário, microchipagem e devolução ao tutor.</p></div><div className="headerActions"><Link className="secondaryLink" href="/assistencia">Assistência Humanitária</Link><Link className="secondaryLink" href="/gestao-riscos">Gestão do Risco</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="statsGrid"><article><strong>{active.length}</strong><span>Animais/grupos sob cuidado</span></article><article><strong>{items.filter(x=>x.status==="VETERINARY").length}</strong><span>Em atendimento veterinário</span></article><article><strong>{items.filter(x=>x.status==="RETURNED").length}</strong><span>Devolvidos ao tutor</span></article><article><strong>{shelters.filter(x=>x.petAreaAvailable).length}</strong><span>Abrigos com área para animais</span></article></section>
  <form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={create}><h2>Novo resgate</h2><div className="formGrid"><label>Ocorrência<select name="incidentId"><option value="">Sem vínculo</option>{incidents.map(x=><option key={x.id} value={x.id}>{x.protocol} · {x.summary}</option>)}</select></label><label>Abrigo<select name="shelterId"><option value="">Sem abrigo</option>{shelters.map(x=><option key={x.id} value={x.id}>{x.name}{x.petAreaAvailable?" · aceita animais":""}</option>)}</select></label><label>Espécie<input name="species" required placeholder="Cão, gato, ave..."/></label><label>Quantidade<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>Nome do animal<input name="animalName"/></label><label>Identificação / características<input name="identification"/></label><label>Tutor/responsável<input name="tutorName"/></label><label>Telefone do tutor<input name="tutorPhone"/></label><label>Local encontrado<input name="foundLocation"/></label><label>Latitude<input name="latitude" type="number" step="any"/></label><label>Longitude<input name="longitude" type="number" step="any"/></label><label>Destino atual<input name="destination"/></label><label>Condição<select name="healthStatus"><option>UNKNOWN</option><option>STABLE</option><option>INJURED</option><option>CRITICAL</option><option>DECEASED</option></select></label><label>Microchip<input name="microchip"/></label><label>Vacinação<input name="vaccinationStatus"/></label></div><label>Observações veterinárias<textarea name="veterinaryNotes"/></label><button className="primaryButton" disabled={busy}>Registrar resgate</button></form>
  <div className="dataGrid" style={{marginTop:18}}>{items.map(x=><article className={x.healthStatus==="CRITICAL"?"warningCard":"card"} key={x.id}><h3>{x.animalName||x.species} · {x.quantity} {x.quantity===1?"animal":"animais"}</h3><p><strong>{statusPt[x.status]??x.status}</strong> · {healthPt[x.healthStatus]??x.healthStatus}{x.protocol?" · "+x.protocol:""}</p><p>{x.identification||"Sem identificação complementar"}</p><p>{x.tutorName?"Tutor: "+x.tutorName:"Tutor não identificado"}{x.tutorPhone?" · "+x.tutorPhone:""}</p><p>{x.shelterName?"Abrigo: "+x.shelterName:x.destination?"Destino: "+x.destination:"Sem destino informado"}</p>{x.microchip&&<p>Microchip: {x.microchip}</p>}{x.vaccinationStatus&&<p>Vacinação: {x.vaccinationStatus}</p>}<p><small>Registrado em {formatDateTimeBR(x.createdAt)}</small></p><button className="secondaryButton" onClick={()=>void changeStatus(x)}>Atualizar situação</button></article>)}</div>
 </main>
}
