import "dotenv/config";
import Fastify from "fastify";
import cookie from "@fastify/cookie";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import rateLimit from "@fastify/rate-limit";
import { authRoutes } from "./routes/auth.js";
import { incidentRoutes } from "./routes/incidents.js";
import { responseRoutes } from "./routes/response.js";
import { fieldRoutes } from "./routes/field.js";
import { commandRoutes } from "./routes/command.js";
import { planningRoutes } from "./routes/planning.js";
import { documentRoutes } from "./routes/documents.js";
import { evaluateSidecArchiveVerifications, evaluateSidecDeadlineAlerts, evaluateSidecResilience, sidecRoutes } from "./routes/sidec.js";
import { continuityRoutes, evaluateContinuityActionAlerts } from "./routes/continuity.js";
const app=Fastify({logger:true,trustProxy:true});
await app.register(helmet);await app.register(cookie);await app.register(rateLimit,{global:false});
await app.register(cors,{origin:process.env.SIGDEC_PUBLIC_URL??"http://localhost:3000",credentials:true});
app.get("/health",async()=>({status:"ok",service:"sigdec-api",version:"1.31.0",timestamp:new Date().toISOString()}));
await app.register(authRoutes);await app.register(incidentRoutes);await app.register(responseRoutes);await app.register(fieldRoutes);await app.register(commandRoutes);await app.register(planningRoutes);await app.register(documentRoutes);await app.register(sidecRoutes);await app.register(continuityRoutes);
app.get("/api/v1",async()=>({name:"SIGDEC API",version:"v1",release:"1.31.0",modules:["auth","ocorrencias","despacho","campo","riscos","monitoramento","alertas","vistorias","documentos","desastres","sco","assistencia-humanitaria","voluntariado","logistica","comunicacoes","s2id","treinamentos","recuperacao","biblioteca","bi","administracao","integracoes","sidec-interoperabilidade","sidec-continuidade","inteligencia-assistiva","auditoria"]}));
await app.listen({port:Number(process.env.PORT??4000),host:process.env.HOST??"0.0.0.0"});
const sidecDeadlineMinutes=Math.max(5,Math.min(1440,Number(process.env.SIDEC_DEADLINE_EVALUATION_MINUTES??60)));
const evaluateDeadlines=()=>evaluateSidecDeadlineAlerts().catch(error=>app.log.error({err:error},"Falha ao avaliar SLAs SIDEC."));
void evaluateDeadlines();
const sidecDeadlineTimer=setInterval(evaluateDeadlines,sidecDeadlineMinutes*60*1000);
sidecDeadlineTimer.unref();
const sidecArchiveVerificationMinutes=Math.max(60,Math.min(10080,Number(process.env.SIDEC_WORM_VERIFICATION_MINUTES??1440)));
const evaluateArchives=()=>evaluateSidecArchiveVerifications().catch(error=>app.log.error({err:error},"Falha ao verificar arquivos WORM SIDEC."));
void evaluateArchives();
const sidecArchiveTimer=setInterval(evaluateArchives,sidecArchiveVerificationMinutes*60*1000);
sidecArchiveTimer.unref();

const sidecResilienceMinutes=Math.max(5,Math.min(1440,Number(process.env.SIDEC_RESILIENCE_EVALUATION_MINUTES??15)));
const evaluateResilience=()=>evaluateSidecResilience().catch(error=>app.log.error({err:error},"Falha ao avaliar resiliência WORM SIDEC."));
void evaluateResilience();
const sidecResilienceTimer=setInterval(evaluateResilience,sidecResilienceMinutes*60*1000);
sidecResilienceTimer.unref();

const continuityActionAlertMinutes=Math.max(5,Math.min(1440,Number(process.env.SIDEC_CONTINUITY_ACTION_ALERT_MINUTES??60)));
const evaluateContinuityActions=()=>evaluateContinuityActionAlerts().catch(error=>app.log.error({err:error},"Falha ao avaliar ações corretivas de continuidade SIDEC."));
void evaluateContinuityActions();
const continuityActionAlertTimer=setInterval(evaluateContinuityActions,continuityActionAlertMinutes*60*1000);
continuityActionAlertTimer.unref();
