"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../lib/release";
import {useRealtimeRefresh} from "../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
const riskPt:Record<string,string>={R1:"Baixo",R2:"Médio",R3:"Alto",R4:"Muito alto"};
export default function Page(){
 const[summary,setSummary]=useState<Row>({}),[areas,setAreas]=useState<Row[]>([]),[projects,setProjects]=useState<Row[]>([]),[nuclei,setNuclei]=useState<Row[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("areas");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[s,a,p,n]=await Promise.all([request("/api/v1/risk-management/summary"),request("/api/v1/risk-areas"),request("/api/v1/mitigation-projects"),request("/api/v1/community-nuclei")]);setSummary(s);setAreas(a.items??[]);setProjects(p.items??[]);setNuclei(n.items??[]);setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar.")}},[request]);
 useEffect(()=>{void load()},[load]);useRealtimeRefresh(()=>{if(!busy)return load()},true,5000);
 async function perform(fn:()=>Promise<void>){setBusy(true);setMsg("");try{await fn();await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 const num=(v:FormDataEntryValue|null)=>{const s=String(v??"").trim().replace(",",".");return s?Number(s):undefined};const opt=(v:FormDataEntryValue|null)=>String(v??"").trim()||undefined;
 async function createArea(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/risk-areas",{method:"POST",body:JSON.stringify({code:String(d.get("code")),name:String(d.get("name")),neighborhood:opt(d.get("neighborhood")),hazardType:String(d.get("hazardType")),riskLevel:String(d.get("riskLevel")),pmrrReference:opt(d.get("pmrrReference")),exposedBuildings:Number(d.get("exposedBuildings")||0),exposedPeople:Number(d.get("exposedPeople")||0),latitude:num(d.get("latitude")),longitude:num(d.get("longitude")),notes:opt(d.get("notes"))})});f.reset();setMsg("Área de risco cadastrada.")})}
 async function areaStatus(id:string,status:string){await perform(()=>request("/api/v1/risk-areas/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})}))}
 async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/mitigation-projects",{method:"POST",body:JSON.stringify({riskAreaId:opt(d.get("riskAreaId")),code:String(d.get("code")),title:String(d.get("title")),interventionType:String(d.get("interventionType")),priority:String(d.get("priority")),responsibleDepartment:opt(d.get("responsibleDepartment")),fundingSource:opt(d.get("fundingSource")),estimatedCost:num(d.get("estimatedCost")),contractedCost:num(d.get("contractedCost")),startsAt:opt(d.get("startsAt")),expectedEndAt:opt(d.get("expectedEndAt")),residualRisk:opt(d.get("residualRisk")),notes:opt(d.get("notes"))})});f.reset();setMsg("Projeto de mitigação cadastrado.")})}
 async function projectStatus(id:string,status:string){await perform(()=>request("/api/v1/mitigation-projects/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})}))}
 async function createNucleus(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);const ids=String(d.get("riskAreaIds")||"").split(",").map(x=>x.trim()).filter(Boolean);await perform(async()=>{await request("/api/v1/community-nuclei",{method:"POST",body:JSON.stringify({code:String(d.get("code")),name:String(d.get("name")),neighborhood:opt(d.get("neighborhood")),coordinatorName:opt(d.get("coordinatorName")),phone:opt(d.get("phone")),email:opt(d.get("email"))??"",membersCount:Number(d.get("membersCount")||0),riskAreaIds:ids,notes:opt(d.get("notes"))})});f.reset();setMsg("NUDEC cadastrado.")})}
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · GESTÃO DO RISCO · {SIGDEC_VERSION_LABEL}</span><h1>Gestão Territorial do Risco</h1><p>PMRR, áreas de risco, mitigação e organização comunitária em uma base única para Ubatuba.</p></div><div className="headerActions"><Link className="secondaryLink" href="/alertas">Alertas e Evacuação</Link><Link className="secondaryLink" href="/danos">Danos / FIDE / DMATE</Link><Link className="secondaryLink" href="/infraestruturas">Infraestruturas</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="statsGrid"><article><strong>{summary.riskAreas??0}</strong><span>Áreas de risco</span></article><article className={(summary.r4Areas??0)>0?"warningCard":""}><strong>{summary.r4Areas??0}</strong><span>Áreas R4</span></article><article><strong>{summary.openMitigationProjects??0}</strong><span>Projetos de mitigação</span></article><article><strong>{summary.activeNuclei??0}</strong><span>NUDECs ativos</span></article></section>
  <div className="adminTabs" style={{marginTop:18}}><button className={tab==="areas"?"active":""} onClick={()=>setTab("areas")}>PMRR / Áreas</button><button className={tab==="mitigation"?"active":""} onClick={()=>setTab("mitigation")}>Projetos de mitigação</button><button className={tab==="nudec"?"active":""} onClick={()=>setTab("nudec")}>NUDEC</button></div>
  {tab==="areas"&&<section className="operationsGrid" style={{marginTop:18}}><form className="incidentForm compactForm" onSubmit={createArea}><h2>Nova área de risco</h2><div className="formGrid"><label>Código<input name="code" required placeholder="PMRR-R4-001"/></label><label>Nome<input name="name" required/></label><label>Bairro<input name="neighborhood"/></label><label>Ameaça<input name="hazardType" required placeholder="Deslizamento, inundação..."/></label><label>Grau<select name="riskLevel" defaultValue="R3">{["R1","R2","R3","R4"].map(x=><option key={x} value={x}>{x} · {riskPt[x]}</option>)}</select></label><label>Referência PMRR<input name="pmrrReference"/></label><label>Imóveis expostos<input name="exposedBuildings" type="number" min="0" defaultValue="0"/></label><label>Pessoas expostas<input name="exposedPeople" type="number" min="0" defaultValue="0"/></label><label>Latitude<input name="latitude" type="number" step="any"/></label><label>Longitude<input name="longitude" type="number" step="any"/></label></div><label>Observações<textarea name="notes"/></label><button className="primaryButton" disabled={busy}>Cadastrar área</button></form><div className="dataGrid">{areas.map(x=><article className={x.riskLevel==="R4"?"warningCard":"card"} key={x.id}><h3>{x.code} · {x.name}</h3><p><strong>{x.riskLevel} · {riskPt[x.riskLevel]}</strong> · {x.hazardType}</p><p>{x.neighborhood??"Bairro não informado"} · {x.exposedBuildings} imóvel(is) · {x.exposedPeople} pessoa(s)</p><p>{x.pmrrReference||"Sem referência PMRR"}</p><div className="headerActions"><button className="secondaryButton" onClick={()=>void areaStatus(x.id,"MONITORING")}>Monitorar</button><button className="secondaryButton" onClick={()=>void areaStatus(x.id,"MITIGATED")}>Mitigada</button></div></article>)}</div></section>}
  {tab==="mitigation"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createProject}><h2>Projeto de redução de risco</h2><div className="formGrid"><label>Área<select name="riskAreaId"><option value="">Geral</option>{areas.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Código<input name="code" required/></label><label>Título<input name="title" required/></label><label>Intervenção<input name="interventionType" required placeholder="Contenção, drenagem..."/></label><label>Prioridade<select name="priority"><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select></label><label>Secretaria responsável<input name="responsibleDepartment"/></label><label>Fonte de recurso<input name="fundingSource"/></label><label>Custo estimado<input name="estimatedCost" type="number" min="0" step="0.01"/></label><label>Custo contratado<input name="contractedCost" type="number" min="0" step="0.01"/></label><label>Início<input name="startsAt" type="date"/></label><label>Conclusão prevista<input name="expectedEndAt" type="date"/></label><label>Risco residual<input name="residualRisk" placeholder="R1, R2..."/></label></div><label>Notas<textarea name="notes"/></label><button className="primaryButton">Cadastrar projeto</button></form><div className="dataGrid" style={{marginTop:18}}>{projects.map(x=><article className={x.priority==="CRITICAL"?"warningCard":"card"} key={x.id}><h3>{x.code} · {x.title}</h3><p><strong>{x.priority}</strong> · {x.status} · {x.interventionType}</p><p>{x.riskAreaCode?x.riskAreaCode+" · ":""}{x.responsibleDepartment??"Responsável não informado"}</p><p>{x.estimatedCost!=null?"Estimado R$ "+Number(x.estimatedCost).toLocaleString("pt-BR",{minimumFractionDigits:2}):"Sem estimativa"}</p><div className="headerActions">{x.status!=="EXECUTION"&&x.status!=="COMPLETED"&&<button className="secondaryButton" onClick={()=>void projectStatus(x.id,"EXECUTION")}>Iniciar</button>}{x.status!=="COMPLETED"&&<button className="secondaryButton" onClick={()=>void projectStatus(x.id,"COMPLETED")}>Concluir</button>}</div></article>)}</div></>}
  {tab==="nudec"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createNucleus}><h2>Novo NUDEC / NUPDEC</h2><div className="formGrid"><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><label>Bairro/comunidade<input name="neighborhood"/></label><label>Coordenador<input name="coordinatorName"/></label><label>Telefone<input name="phone"/></label><label>E-mail<input name="email" type="email"/></label><label>Integrantes<input name="membersCount" type="number" min="0" defaultValue="0"/></label><label>IDs das áreas de risco, separados por vírgula<input name="riskAreaIds"/></label></div><label>Notas<textarea name="notes"/></label><button className="primaryButton">Cadastrar núcleo</button></form><div className="dataGrid" style={{marginTop:18}}>{nuclei.map(x=><article className="card" key={x.id}><h3>{x.code} · {x.name}</h3><p>{x.neighborhood??"—"} · {x.membersCount} integrante(s)</p><p>{x.coordinatorName?"Coordenação: "+x.coordinatorName:"Sem coordenador informado"}</p><p>{x.active?"Ativo":"Inativo"}</p></article>)}</div></>}
 </main>
}
