"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../../lib/release";
import {formatDateTimeBR} from "../../lib/datetime";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
export default function Page(){
 const[items,setItems]=useState<Row[]>([]),[q,setQ]=useState(""),[jurisdiction,setJurisdiction]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const params=new URLSearchParams();if(q.trim())params.set("q",q.trim());if(jurisdiction)params.set("jurisdiction",jurisdiction);params.set("limit","500");const r=await request("/api/v1/legal/norms?"+params);setItems(r.items??[]);setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar base legal.")}},[request,q,jurisdiction]);
 useEffect(()=>{void load()},[load]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),topics=String(d.get("topics")||"").split(",").map(x=>x.trim()).filter(Boolean);setBusy(true);try{await request("/api/v1/legal/norms",{method:"POST",body:JSON.stringify({jurisdiction:String(d.get("jurisdiction")),stateCode:String(d.get("stateCode")||""),municipality:String(d.get("municipality")||""),normType:String(d.get("normType")),normNumber:String(d.get("normNumber")),normYear:String(d.get("normYear")||"").trim()?Number(d.get("normYear")):undefined,title:String(d.get("title")),summary:String(d.get("summary")||""),status:"ACTIVE",sourceUrl:String(d.get("sourceUrl")),officialSource:String(d.get("officialSource")),topics,verificationNotes:String(d.get("verificationNotes")||"")})});f.reset();setMsg("Norma cadastrada/verificada.");await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha ao cadastrar norma.")}finally{setBusy(false)}}
 const grouped=useMemo(()=>({municipal:items.filter(x=>x.jurisdiction==="MUNICIPAL"),state:items.filter(x=>x.jurisdiction==="STATE"),federal:items.filter(x=>x.jurisdiction==="FEDERAL")}),[items]);
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · INTELIGÊNCIA JURÍDICA · {SIGDEC_VERSION_LABEL}</span><h1>Base Legal e Normativa</h1><p>Catálogo versionável para Defesa Civil, urbanismo, zoneamento, habitação, meio ambiente, saneamento, infraestrutura e demais matérias correlatas.</p></div><div className="headerActions"><Link className="secondaryLink" href="/inteligencia">Inteligência / Relatórios</Link><Link className="secondaryLink" href="/administracao">Administração</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="warningCard"><strong>Regra de uso</strong><p>O catálogo auxilia a pesquisa e a IA, mas não substitui conferência da publicação oficial, vigência, alterações, revogações, regulamentação ou análise jurídica quando necessária.</p></section>
  <section className="statsGrid"><article><strong>{items.length}</strong><span>Normas carregadas</span></article><article><strong>{grouped.municipal.length}</strong><span>Municipais</span></article><article><strong>{grouped.state.length}</strong><span>Estaduais</span></article><article><strong>{grouped.federal.length}</strong><span>Federais</span></article></section>
  <section className="incidentForm compactForm" style={{marginTop:18}}><div className="formGrid"><label>Pesquisar<input value={q} onChange={e=>setQ(e.target.value)} placeholder="risco, zoneamento, habitação, lei..."/></label><label>Esfera<select value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}><option value="">Todas</option><option value="MUNICIPAL">Municipal</option><option value="STATE">Estadual</option><option value="FEDERAL">Federal</option></select></label></div></section>
  <div className="dataGrid" style={{marginTop:18}}>{items.map(x=><article className="card" key={x.id}><span className="eyebrow">{x.jurisdiction}{x.stateCode?" · "+x.stateCode:""}{x.municipality?" · "+x.municipality:""}</span><h3>{x.normType} {x.normNumber}{x.normYear?"/"+x.normYear:""} · {x.title}</h3><p>{x.summary||"Sem resumo cadastrado."}</p><p><strong>Temas:</strong> {(x.topics??[]).join(" · ")||"—"}</p><p><small>Fonte: {x.officialSource} · verificada {x.verifiedAt?formatDateTimeBR(x.verifiedAt):"não registrada"}</small></p><a className="secondaryLink" href={x.sourceUrl} target="_blank" rel="noreferrer">Abrir fonte oficial ↗</a></article>)}</div>
  <section className="detailSection" style={{marginTop:24}}><h2>Cadastrar/atualizar norma</h2><form className="incidentForm compactForm" onSubmit={add}><div className="formGrid"><label>Esfera<select name="jurisdiction"><option>MUNICIPAL</option><option>STATE</option><option>FEDERAL</option></select></label><label>UF<input name="stateCode" defaultValue="SP" maxLength={2}/></label><label>Município<input name="municipality" defaultValue="Ubatuba"/></label><label>Tipo<input name="normType" required placeholder="Lei, Decreto, Resolução..."/></label><label>Número<input name="normNumber" required/></label><label>Ano<input name="normYear" type="number" min="1800" max="2200"/></label><label>Título<input name="title" required/></label><label>Fonte oficial<input name="officialSource" required defaultValue="Prefeitura Municipal de Ubatuba"/></label><label>URL oficial<input name="sourceUrl" type="url" required/></label></div><label>Temas, separados por vírgula<input name="topics" placeholder="defesa_civil, urbanismo, zoneamento, meio_ambiente"/></label><label>Resumo<textarea name="summary"/></label><label>Nota de verificação<textarea name="verificationNotes" placeholder="Alterações consolidadas, revogações, observações..."/></label><button className="primaryButton" disabled={busy}>Salvar norma</button></form></section>
 </main>
}
