"use client";
import Link from "next/link";
import{FormEvent,useCallback,useEffect,useState}from"react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Household={id:string;responsibleName:string;condition:string;adults:number;children:number;elderly:number;personsWithDisability:number;shelterName?:string|null;protocol?:string|null};
type Item={id:string;code:string;name:string;unit:string;category:string;balance:number};
type Delivery={id:string;deliveredAt:string;recipientName:string;notes?:string|null;protocol?:string|null;duplicateAcknowledged:boolean;duplicateReason?:string|null;items:Array<{itemId:string;name:string;unit:string;quantity:number}>};
type Shelter={id:string;name:string;addressLine:string|null;neighborhood:string|null;capacityPeople:number;status:string};

export default function Page(){
 const[households,setHouseholds]=useState<Household[]>([]),[stock,setStock]=useState<Item[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[shelters,setShelters]=useState<Shelter[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[selectedHousehold,setSelectedHousehold]=useState("");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`${API}${path}`,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";return null}const body=await r.json().catch(()=>({}));return {ok:r.ok,status:r.status,body}},[]);
 const load=useCallback(async()=>{const [h,i,d,s]=await Promise.all([request("/api/v1/humanitarian/households"),request("/api/v1/inventory/items"),request("/api/v1/humanitarian/deliveries"),request("/api/v1/humanitarian/shelters")]);if(h?.ok)setHouseholds(h.body.items??[]);if(i?.ok)setStock(i.body.items??[]);if(d?.ok)setDeliveries(d.body.items??[]);if(s?.ok)setShelters(s.body.items??[])},[request]);
 useEffect(()=>{void load()},[load]);
 async function submitHousehold(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const body={shelterId:String(f.get("shelterId")||"")||undefined,responsibleName:String(f.get("responsibleName")||""),phone:String(f.get("phone")||"")||undefined,condition:String(f.get("condition")),adults:Number(f.get("adults")||0),children:Number(f.get("children")||0),elderly:Number(f.get("elderly")||0),personsWithDisability:Number(f.get("pcd")||0),addressOrigin:String(f.get("addressOrigin")||"")||undefined,notes:String(f.get("notes")||"")||undefined};const r=await request("/api/v1/humanitarian/households",{method:"POST",body:JSON.stringify(body)});setBusy(false);if(!r?.ok){setMsg("Não foi possível registrar a família.");return}e.currentTarget.reset();setMsg("Família registrada.");await load()}
 async function stockEntry(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const body={itemId:String(f.get("itemId")),movementType:"IN",quantity:Number(f.get("quantity")||0),reference:String(f.get("reference")||"")||undefined,notes:"Entrada registrada pela Assistência Humanitária"};const r=await request("/api/v1/inventory/movements",{method:"POST",body:JSON.stringify(body)});setBusy(false);if(!r?.ok){setMsg(r?.body?.message??"Não foi possível registrar a entrada.");return}e.currentTarget.reset();setMsg("Entrada de estoque registrada.");await load()}
 async function createShelter(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const form=e.currentTarget,f=new FormData(form);const r=await request("/api/v1/humanitarian/shelters",{method:"POST",body:JSON.stringify({name:String(f.get("name")||""),addressLine:String(f.get("addressLine")||"")||undefined,neighborhood:String(f.get("neighborhood")||"")||undefined,capacityPeople:Number(f.get("capacityPeople")||0),status:String(f.get("status"))})});setBusy(false);if(!r?.ok){setMsg(r?.body?.message??"Não foi possível cadastrar o abrigo.");return}form.reset();setMsg("Abrigo cadastrado.");await load()}
 async function sendDelivery(body:any){return request("/api/v1/humanitarian/deliveries",{method:"POST",body:JSON.stringify(body)})}
 async function delivery(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMsg("");const f=new FormData(e.currentTarget);const householdId=String(f.get("householdId")||"")||undefined;const household=households.find(x=>x.id===householdId);const body:any={householdId,recipientName:String(f.get("recipientName")||household?.responsibleName||""),notes:String(f.get("notes")||"")||undefined,items:[{itemId:String(f.get("itemId")),quantity:Number(f.get("quantity")||0)}],duplicateAcknowledged:false};let r=await sendDelivery(body);if(r?.status===409&&r.body?.error==="POSSIBLE_DUPLICATE_DELIVERY"){const confirm=window.confirm("O SIGDEC encontrou entrega recente com item coincidente para este beneficiário. Deseja registrar nova entrega mesmo assim?");if(confirm){const reason=window.prompt("Justifique a nova entrega:")?.trim();if(reason&&reason.length>=5){r=await sendDelivery({...body,duplicateAcknowledged:true,duplicateReason:reason})}else{setBusy(false);setMsg("Entrega não registrada: a justificativa é obrigatória.");return}}}
 setBusy(false);if(!r?.ok){setMsg(r?.body?.error==="INSUFFICIENT_STOCK"?`Estoque insuficiente. Saldo disponível: ${r.body.balance??0}.`:r?.body?.message??"Não foi possível registrar a entrega.");return}
 e.currentTarget.reset();setSelectedHousehold("");setMsg("Entrega registrada e estoque baixado.");await load()}
 const selected=households.find(x=>x.id===selectedHousehold);
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · ASSISTÊNCIA HUMANITÁRIA · v1.41</span><h1>Assistência Humanitária</h1><p>Famílias, desalojados/desabrigados, estoque, entregas e prevenção de duplicidade.</p></div><Link className="secondaryLink" href="/painel">Painel</Link></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="operationsGrid">
   <form id="familias" className="incidentForm compactForm" onSubmit={submitHousehold}><h2>Registrar família</h2><label>Responsável<input name="responsibleName" required/></label><label>Telefone<input name="phone"/></label><label>Condição<select name="condition"><option value="DISPLACED">Desalojada</option><option value="HOMELESS">Desabrigada</option></select></label><label>Abrigo<select name="shelterId"><option value="">Sem abrigo vinculado</option>{shelters.filter(x=>x.status==="OPEN"||x.status==="STANDBY").map(x=><option key={x.id} value={x.id}>{x.name} · {x.status}</option>)}</select></label><div className="formGrid"><label>Adultos<input name="adults" type="number" min="0" defaultValue="0"/></label><label>Crianças<input name="children" type="number" min="0" defaultValue="0"/></label><label>Idosos<input name="elderly" type="number" min="0" defaultValue="0"/></label><label>PCD<input name="pcd" type="number" min="0" defaultValue="0"/></label></div><label>Endereço de origem<input name="addressOrigin"/></label><label>Observações<textarea name="notes"/></label><button className="primaryButton" disabled={busy}>{busy?"Salvando...":"Registrar família"}</button></form>
   <div>
    <form id="entregas" className="incidentForm compactForm" onSubmit={delivery}><h2>Registrar entrega</h2><label>Família<select name="householdId" value={selectedHousehold} onChange={e=>setSelectedHousehold(e.target.value)}><option value="">Entrega sem família vinculada</option>{households.map(x=><option key={x.id} value={x.id}>{x.responsibleName} · {x.condition==="HOMELESS"?"desabrigada":"desalojada"}</option>)}</select></label><label>Recebedor<input name="recipientName" defaultValue={selected?.responsibleName??""} key={selectedHousehold||"recipient"} required/></label><label>Item<select name="itemId" required><option value="">Selecionar</option>{stock.map(x=><option key={x.id} value={x.id}>{x.name} · saldo {Number(x.balance).toFixed(2)} {x.unit}</option>)}</select></label><label>Quantidade<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Observações<textarea name="notes"/></label><button className="primaryButton" disabled={busy}>Registrar entrega e baixar estoque</button></form>
    <form id="estoque" className="incidentForm compactForm" style={{marginTop:12}} onSubmit={stockEntry}><h2>Entrada de estoque</h2><label>Item<select name="itemId" required><option value="">Selecionar</option>{stock.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Quantidade<input name="quantity" type="number" min="0.01" step="0.01" required/></label><label>Referência / doação<input name="reference"/></label><button className="secondaryLink" disabled={busy}>Registrar entrada</button></form>
   </div>
  </section>
  <section id="abrigos" style={{marginTop:18}}><h2>Abrigos</h2><form className="incidentForm compactForm" onSubmit={createShelter}><div className="formGrid"><label>Nome<input name="name" required minLength={2}/></label><label>Capacidade de pessoas<input name="capacityPeople" type="number" required min="0" defaultValue="0"/></label><label>Endereço<input name="addressLine"/></label><label>Bairro<input name="neighborhood"/></label><label>Situação<select name="status"><option value="STANDBY">Preparado</option><option value="OPEN">Aberto</option><option value="FULL">Lotado</option><option value="CLOSED">Fechado</option></select></label></div><button className="primaryButton" disabled={busy}>Cadastrar abrigo</button></form><div className="dataGrid">{shelters.map(x=><article className="card" key={x.id}><h3>{x.name}</h3><p>{x.status} · capacidade {x.capacityPeople} pessoas</p><p>{[x.addressLine,x.neighborhood].filter(Boolean).join(" · ")}</p></article>)}</div></section>
  <section style={{marginTop:18}}><h2>Estoque humanitário</h2><div className="dataGrid">{stock.map(x=><article className={Number(x.balance)<=0?"warningCard":"card"} key={x.id}><h2>{x.name}</h2><p><strong>{Number(x.balance).toFixed(2)} {x.unit}</strong> · {x.category}</p><p>{x.code}</p></article>)}</div></section>
  <section style={{marginTop:18}}><h2>Famílias acompanhadas</h2><div className="dataGrid">{households.length===0?<div className="infoCard">Nenhuma família registrada.</div>:households.map(x=><article className="card" key={x.id}><h2>{x.responsibleName}</h2><p><strong>{x.condition==="HOMELESS"?"Desabrigada":"Desalojada"}</strong>{x.protocol?` · ${x.protocol}`:""}</p><p>Adultos: {x.adults} · Crianças: {x.children} · Idosos: {x.elderly} · PCD: {x.personsWithDisability}</p><p>{x.shelterName?`Abrigo: ${x.shelterName}`:"Sem abrigo vinculado"}</p></article>)}</div></section>
  <section style={{marginTop:18}}><h2>Entregas recentes</h2><div className="dataGrid">{deliveries.length===0?<div className="infoCard">Nenhuma entrega registrada.</div>:deliveries.map(x=><article className={x.duplicateAcknowledged?"warningCard":"card"} key={x.id}><h2>{x.recipientName}</h2><p>{new Date(x.deliveredAt).toLocaleString("pt-BR")}{x.protocol?` · ${x.protocol}`:""}</p><p>{x.items.map(i=>`${i.name}: ${i.quantity} ${i.unit}`).join(" · ")}</p>{x.duplicateAcknowledged&&<p><strong>Entrega após alerta de duplicidade:</strong> {x.duplicateReason}</p>}{x.notes&&<p>{x.notes}</p>}</article>)}</div></section>
 </main>;
}
