"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Contact={id:string;kind:"PHONE"|"EMAIL";value:string;label?:string|null;phoneType?:string|null;isWhatsapp:boolean;isPrimary:boolean};
type Responsible={id:string;fullName:string;roleLabel?:string|null;addressLine?:string|null;neighborhood?:string|null;contacts:Contact[]};
export function ShelterResponsibles({shelterId}:{shelterId:string}){
 const[items,setItems]=useState<Responsible[]>([]),[msg,setMsg]=useState("");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});return{ok:r.ok,body:await r.json().catch(()=>({}))}},[]);
 const load=useCallback(async()=>{const r=await request("/api/v1/humanitarian/shelters/"+shelterId+"/responsibles");if(r.ok)setItems(r.body.items??[])},[request,shelterId]);
 useEffect(()=>{void load()},[load]);
 async function addResponsible(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),r=await request("/api/v1/humanitarian/shelters/"+shelterId+"/responsibles",{method:"POST",body:JSON.stringify({fullName:String(f.get("fullName")||""),roleLabel:String(f.get("roleLabel")||"")||undefined,addressLine:String(f.get("addressLine")||"")||undefined,neighborhood:String(f.get("neighborhood")||"")||undefined})});if(r.ok){e.currentTarget.reset();setMsg("Responsável adicionado.");await load()}else setMsg("Não foi possível adicionar o responsável.");}
 async function addContact(e:FormEvent<HTMLFormElement>,responsibleId:string,kind:"PHONE"|"EMAIL"){e.preventDefault();const f=new FormData(e.currentTarget),r=await request("/api/v1/shelter-responsibles/"+responsibleId+"/contacts",{method:"POST",body:JSON.stringify({kind,value:String(f.get("value")||""),label:String(f.get("label")||"")||undefined,phoneType:kind==="PHONE"?String(f.get("phoneType")||"MOBILE"):undefined,isWhatsapp:kind==="PHONE"&&f.get("whatsapp")==="on",isPrimary:f.get("primary")==="on"})});if(r.ok){e.currentTarget.reset();await load()}else setMsg("Contato inválido ou já cadastrado.");}
 async function editContact(c:Contact){const value=prompt(c.kind==="PHONE"?"Editar telefone:":"Editar e-mail:",c.value)?.trim();if(!value)return;const r=await request("/api/v1/contact-points/"+c.id,{method:"PATCH",body:JSON.stringify({kind:c.kind,value,label:c.label??undefined,phoneType:c.kind==="PHONE"?(c.phoneType??"MOBILE"):undefined,isWhatsapp:c.isWhatsapp,isPrimary:c.isPrimary})});if(r.ok)await load();else setMsg("Não foi possível editar o contato.");}
 async function removeContact(id:string){if(!confirm("Excluir este contato?"))return;const r=await request("/api/v1/contact-points/"+id,{method:"DELETE"});if(r.ok)await load();}
 async function editResponsible(x:Responsible){const fullName=prompt("Nome do responsável:",x.fullName)?.trim();if(!fullName)return;const roleLabel=prompt("Função/vínculo:",x.roleLabel??"")??"";const r=await request("/api/v1/shelter-responsibles/"+x.id,{method:"PATCH",body:JSON.stringify({fullName,roleLabel})});if(r.ok)await load();}
 async function removeResponsible(id:string){if(!confirm("Excluir este responsável do abrigo?"))return;const r=await request("/api/v1/shelter-responsibles/"+id,{method:"DELETE"});if(r.ok)await load();}
 return <div className="incidentForm compactForm" style={{marginTop:10}}><h4>Responsáveis do abrigo</h4>{items.length<2&&<p className="fieldWarning">Cadastre ao menos dois responsáveis para melhor prontidão operacional.</p>}{msg&&<small>{msg}</small>}
 <form onSubmit={addResponsible}><div className="formGrid"><label>Nome<input name="fullName" required/></label><label>Função/vínculo<input name="roleLabel"/></label><label>Endereço<input name="addressLine"/></label><label>Bairro<input name="neighborhood"/></label></div><button className="secondaryButton">Adicionar responsável</button></form>
 {items.map(x=><div className="card" key={x.id} style={{marginTop:8}}><strong>{x.fullName}</strong>{x.roleLabel&&<span> · {x.roleLabel}</span>} <button type="button" title="Editar responsável" onClick={()=>void editResponsible(x)}>✏️</button> <button type="button" title="Excluir responsável" onClick={()=>void removeResponsible(x.id)}>−</button>
 <p>{[x.addressLine,x.neighborhood].filter(Boolean).join(" · ")}</p>
 {x.contacts.map(c=><div key={c.id}><span>{c.kind==="PHONE"?"📱":"✉️"} {c.value}{c.isWhatsapp?" · WhatsApp":""}{c.isPrimary?" · Principal":""}</span> <button type="button" title="Editar" onClick={()=>void editContact(c)}>✏️</button> <button type="button" title="Excluir" onClick={()=>void removeContact(c.id)}>−</button></div>)}
 <form onSubmit={e=>void addContact(e,x.id,"PHONE")}><div className="formGrid"><label>Telefone<input name="value" required/></label><label>Tipo<select name="phoneType"><option value="MOBILE">Celular</option><option value="LANDLINE">Fixo</option></select></label><label><input type="checkbox" name="whatsapp"/> WhatsApp</label><label><input type="checkbox" name="primary"/> Principal</label></div><button className="secondaryButton">Adicionar telefone</button></form>
 <form onSubmit={e=>void addContact(e,x.id,"EMAIL")}><div className="formGrid"><label>E-mail<input name="value" type="email" required/></label><label>Descrição<input name="label" placeholder="Pessoal, institucional..."/></label><label><input type="checkbox" name="primary"/> Principal</label></div><button className="secondaryButton">Adicionar e-mail</button></form>
 </div>)}</div>;
}
