"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../lib/release";
import {formatDateTimeBR} from "../lib/datetime";
import {useRealtimeRefresh} from "../lib/use-realtime-refresh";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Row=Record<string,any>;
export default function Page(){
 const[areas,setAreas]=useState<Row[]>([]),[assets,setAssets]=useState<Row[]>([]),[warnings,setWarnings]=useState<Row[]>([]),[routes,setRoutes]=useState<Row[]>([]),[bulletins,setBulletins]=useState<Row[]>([]),[shelters,setShelters]=useState<Row[]>([]);
 const[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("warnings");
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[a,wa,w,er,b,sh]=await Promise.all([request("/api/v1/risk-areas"),request("/api/v1/warning-assets"),request("/api/v1/warnings"),request("/api/v1/evacuation-routes"),request("/api/v1/public-bulletins"),request("/api/v1/shelters/readiness")]);setAreas(a.items??[]);setAssets(wa.items??[]);setWarnings(w.items??[]);setRoutes(er.items??[]);setBulletins(b.items??[]);setShelters(sh.items??[]);setMsg("")}catch(e){setMsg(e instanceof Error?e.message:"Falha ao carregar.")}},[request]);
 useEffect(()=>{void load()},[load]);useRealtimeRefresh(()=>{if(!busy)return load()},true,5000);
 async function perform(fn:()=>Promise<void>){setBusy(true);setMsg("");try{await fn();await load()}catch(e){setMsg(e instanceof Error?e.message:"Falha na operação.")}finally{setBusy(false)}}
 const num=(v:FormDataEntryValue|null)=>{const s=String(v??"").trim().replace(",",".");return s?Number(s):undefined};const opt=(v:FormDataEntryValue|null)=>String(v??"").trim()||undefined;
 async function createAsset(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/warning-assets",{method:"POST",body:JSON.stringify({code:String(d.get("code")),name:String(d.get("name")),assetType:String(d.get("assetType")),addressLine:opt(d.get("addressLine")),neighborhood:opt(d.get("neighborhood")),latitude:num(d.get("latitude")),longitude:num(d.get("longitude")),batteryPercent:num(d.get("batteryPercent")),responsibleName:opt(d.get("responsibleName")),responsiblePhone:opt(d.get("responsiblePhone")),nextTestAt:opt(d.get("nextTestAt")),notes:opt(d.get("notes"))})});f.reset();setMsg("Ativo de alerta cadastrado.")})}
 async function testAsset(id:string){await perform(()=>request("/api/v1/warning-assets/"+id+"/test",{method:"POST",body:"{}"}))}
 async function createWarning(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),channels=String(d.get("channels")||"").split(",").map(x=>x.trim()).filter(Boolean);await perform(async()=>{await request("/api/v1/warnings",{method:"POST",body:JSON.stringify({riskAreaId:opt(d.get("riskAreaId")),severity:String(d.get("severity")),title:String(d.get("title")),message:String(d.get("message")),instruction:opt(d.get("instruction")),capIdentifier:opt(d.get("capIdentifier")),channels})});f.reset();setMsg("Alerta preparado.")})}
 async function warningStatus(id:string,status:string){await perform(()=>request("/api/v1/warnings/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})}))}
 async function createRoute(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform(async()=>{await request("/api/v1/evacuation-routes",{method:"POST",body:JSON.stringify({riskAreaId:opt(d.get("riskAreaId")),code:String(d.get("code")),name:String(d.get("name")),originText:opt(d.get("originText")),destinationText:String(d.get("destinationText")),distanceMeters:num(d.get("distanceMeters")),accessible:d.get("accessible")==="on",notes:opt(d.get("notes"))})});f.reset();setMsg("Rota de evacuação cadastrada.")})}
 async function createBulletin(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f),channels=String(d.get("channels")||"").split(",").map(x=>x.trim()).filter(Boolean);await perform(async()=>{await request("/api/v1/public-bulletins",{method:"POST",body:JSON.stringify({title:String(d.get("title")),content:String(d.get("content")),audience:opt(d.get("audience")),channels})});f.reset();setMsg("Boletim criado.")})}
 async function bulletinStatus(id:string,status:string){await perform(()=>request("/api/v1/public-bulletins/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})}))}
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · ALERTA E EVACUAÇÃO · {SIGDEC_VERSION_LABEL}</span><h1>Central de Alertas, Sirenes e Evacuação</h1><p>Preparação, testes, alertas, rotas de fuga, pontos seguros e comunicação pública.</p></div><div className="headerActions"><Link className="secondaryLink" href="/gestao-riscos">Gestão do Risco</Link><Link className="secondaryLink" href="/campo?monitor=1">Monitor</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {msg&&<section className="infoCard">{msg}</section>}
  <section className="statsGrid"><article><strong>{assets.filter(x=>x.status==="OPERATIONAL").length}</strong><span>Ativos operacionais</span></article><article className={warnings.some(x=>x.status==="PUBLISHED"&&x.severity==="EMERGENCY")?"warningCard":""}><strong>{warnings.filter(x=>x.status==="PUBLISHED").length}</strong><span>Alertas publicados</span></article><article><strong>{routes.filter(x=>x.status==="ACTIVE").length}</strong><span>Rotas ativas</span></article><article><strong>{shelters.filter(x=>["OPEN","STANDBY"].includes(x.status)).length}</strong><span>Abrigos preparados/abertos</span></article></section>
  <div className="adminTabs" style={{marginTop:18}}><button className={tab==="warnings"?"active":""} onClick={()=>setTab("warnings")}>Alertas</button><button className={tab==="assets"?"active":""} onClick={()=>setTab("assets")}>Sirenes e ativos</button><button className={tab==="routes"?"active":""} onClick={()=>setTab("routes")}>Evacuação</button><button className={tab==="bulletins"?"active":""} onClick={()=>setTab("bulletins")}>Boletins públicos</button></div>
  {tab==="warnings"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createWarning}><h2>Novo alerta</h2><label>Área de risco<select name="riskAreaId"><option value="">Sem área específica</option>{areas.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Severidade<select name="severity"><option>WATCH</option><option>WARNING</option><option>EMERGENCY</option><option>INFO</option></select></label><label>Título<input name="title" required/></label><label>Mensagem<textarea name="message" required/></label><label>Instrução à população<textarea name="instruction"/></label><label>Canais separados por vírgula<input name="channels" required defaultValue="sirene, rádio, redes sociais"/></label><label>Identificador CAP<input name="capIdentifier"/></label><button className="primaryButton">Preparar alerta</button></form><div className="dataGrid" style={{marginTop:18}}>{warnings.map(x=><article className={x.severity==="EMERGENCY"?"warningCard":"card"} key={x.id}><h3>{x.title}</h3><p><strong>{x.severity}</strong> · {x.status}{x.riskAreaCode?" · "+x.riskAreaCode:""}</p><p>{x.message}</p>{x.instruction&&<p><strong>Orientação:</strong> {x.instruction}</p>}<p><small>{x.publishedAt?"Publicado em "+formatDateTimeBR(x.publishedAt):"Ainda não publicado"}</small></p><div className="headerActions"><a className="secondaryLink" href={API+"/api/v1/warnings/"+x.id+"/cap"} target="_blank" rel="noreferrer">Baixar CAP</a>{x.status==="DRAFT"&&<button className="primaryButton" onClick={()=>void warningStatus(x.id,"PUBLISHED")}>Publicar</button>}{x.status==="PUBLISHED"&&<button className="secondaryButton" onClick={()=>void warningStatus(x.id,"ENDED")}>Encerrar</button>}</div></article>)}</div></>}
  {tab==="assets"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createAsset}><h2>Novo ativo de alerta</h2><div className="formGrid"><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><label>Tipo<select name="assetType"><option>SIREN</option><option>LOUDSPEAKER</option><option>RADIO_BASE</option><option>CELL_BROADCAST</option><option>SMS</option><option>OTHER</option></select></label><label>Bairro<input name="neighborhood"/></label><label>Endereço<input name="addressLine"/></label><label>Bateria %<input name="batteryPercent" type="number" min="0" max="100"/></label><label>Responsável<input name="responsibleName"/></label><label>Contato<input name="responsiblePhone"/></label><label>Próximo teste<input name="nextTestAt" type="datetime-local"/></label><label>Latitude<input name="latitude" type="number" step="any"/></label><label>Longitude<input name="longitude" type="number" step="any"/></label></div><label>Notas<textarea name="notes"/></label><button className="primaryButton">Cadastrar ativo</button></form><div className="dataGrid" style={{marginTop:18}}>{assets.map(x=><article className={x.status==="OPERATIONAL"?"card":"warningCard"} key={x.id}><h3>{x.code} · {x.name}</h3><p>{x.assetType} · <strong>{x.status}</strong></p><p>{x.neighborhood??"—"}{x.batteryPercent!=null?" · bateria "+x.batteryPercent+"%":""}</p><p><small>Último teste: {x.lastTestedAt?formatDateTimeBR(x.lastTestedAt):"não registrado"}</small></p><button className="secondaryButton" onClick={()=>void testAsset(x.id)}>Registrar teste OK</button></article>)}</div></>}
  {tab==="routes"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createRoute}><h2>Nova rota de evacuação</h2><div className="formGrid"><label>Área de risco<select name="riskAreaId"><option value="">Sem vínculo</option>{areas.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Código<input name="code" required/></label><label>Nome<input name="name" required/></label><label>Origem<input name="originText"/></label><label>Destino / ponto seguro<input name="destinationText" required/></label><label>Distância (m)<input name="distanceMeters" type="number" min="0"/></label><label><input name="accessible" type="checkbox"/> Rota acessível</label></div><label>Notas<textarea name="notes"/></label><button className="primaryButton">Cadastrar rota</button></form><div className="dataGrid" style={{marginTop:18}}>{routes.map(x=><article className="card" key={x.id}><h3>{x.code} · {x.name}</h3><p>{x.riskAreaCode??"Sem área"} · {x.originText||"Origem não descrita"} → <strong>{x.destinationText}</strong></p><p>{x.distanceMeters?x.distanceMeters+" m · ":""}{x.accessible?"acessível":"acessibilidade não informada"} · {x.status}</p></article>)}</div><section style={{marginTop:20}}><h2>Abrigos e pontos de acolhimento</h2><div className="dataGrid">{shelters.map(x=><article className="card" key={x.id}><h3>{x.name}</h3><p>{x.currentPeople}/{x.capacityPeople} pessoa(s) · {x.status}</p><p>{[x.accessible?"♿ acessível":null,x.generatorAvailable?"gerador":null,x.petAreaAvailable?"área para animais":null].filter(Boolean).join(" · ")||"Prontidão não atualizada"}</p></article>)}</div></section></>}
  {tab==="bulletins"&&<><form className="incidentForm compactForm" style={{marginTop:18}} onSubmit={createBulletin}><h2>Novo boletim público</h2><label>Título<input name="title" required/></label><label>Público-alvo<input name="audience" defaultValue="População em geral"/></label><label>Conteúdo<textarea name="content" required rows={6}/></label><label>Canais separados por vírgula<input name="channels" defaultValue="site, redes sociais, imprensa"/></label><button className="primaryButton">Criar boletim</button></form><div className="dataGrid" style={{marginTop:18}}>{bulletins.map(x=><article className="card" key={x.id}><h3>{x.title}</h3><p><strong>{x.status}</strong> · {x.audience??"Público geral"}</p><p>{x.content}</p><div className="headerActions">{x.status==="DRAFT"&&<button className="secondaryButton" onClick={()=>void bulletinStatus(x.id,"APPROVED")}>Aprovar</button>}{["DRAFT","APPROVED"].includes(x.status)&&<button className="primaryButton" onClick={()=>void bulletinStatus(x.id,"PUBLISHED")}>Publicar</button>}</div></article>)}</div></>}
 </main>
}
