"use client";
import { formatDateTimeBR } from "../lib/datetime";
import Link from "next/link";
import{FormEvent,useCallback,useEffect,useState}from"react";
const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Feature={code:string;label:string;enabled:boolean;updatedAt?:string|null};
type Integration={id:string;name:string;integrationType:"API"|"WEBHOOK"|"IMPORT"|"EXPORT";endpointUrl?:string|null;active:boolean;config?:Record<string,unknown>;webhookSecretConfigured?:boolean;lastDeliveryAt?:string|null;deliveryFailureCount?:number;pendingDeliveries?:number;failedDeliveries?:number};
export default function AdministrationPage(){
 const[features,setFeatures]=useState<Feature[]>([]),[integrations,setIntegrations]=useState<Integration[]>([]),[message,setMessage]=useState(""),[secretNotice,setSecretNotice]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(`${API}${path}`,{credentials:"include",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";return null}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na operação.");return b},[]);
 const load=useCallback(async()=>{try{const[f,i]=await Promise.all([request("/api/v1/admin/features"),request("/api/v1/admin/integrations")]);if(f)setFeatures(f.items??[]);if(i)setIntegrations(i.items??[])}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar administração.")}},[request]);
 useEffect(()=>{void load()},[load]);
 async function toggleFeature(item:Feature){setBusy(true);setMessage("");try{await request(`/api/v1/admin/features/${item.code}`,{method:"PUT",body:JSON.stringify({enabled:!item.enabled})});setMessage(`${item.label}: ${!item.enabled?"ativado":"desativado"}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function addIntegration(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");setSecretNotice("");const f=new FormData(e.currentTarget);try{const result=await request("/api/v1/admin/integrations",{method:"POST",body:JSON.stringify({name:String(f.get("name")),integrationType:String(f.get("type")),endpointUrl:String(f.get("url")||"")||undefined,active:true,config:{description:String(f.get("description")||""),eventPrefix:String(f.get("eventPrefix")||""),includeData:f.get("includeData")==="on"}})});e.currentTarget.reset();setMessage("Integração cadastrada.");if(result?.webhookSecret)setSecretNotice(`Segredo do webhook (salve agora): ${result.webhookSecret}`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function toggleIntegration(item:Integration){setBusy(true);try{await request(`/api/v1/admin/integrations/${item.id}/status`,{method:"PATCH",body:JSON.stringify({active:!item.active})});await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function rotateSecret(item:Integration){setBusy(true);setSecretNotice("");try{const r=await request(`/api/v1/admin/integrations/${item.id}/rotate-secret`,{method:"POST"});if(r?.webhookSecret)setSecretNotice(`Novo segredo de ${item.name} (salve agora): ${r.webhookSecret}`);setMessage("Segredo rotacionado. O segredo anterior deixou de validar novas entregas.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha ao rotacionar segredo.")}finally{setBusy(false)}}
 async function testWebhook(item:Integration){setBusy(true);setMessage("");try{const r=await request(`/api/v1/admin/integrations/${item.id}/test`,{method:"POST"});setMessage(r?.success?"Webhook testado com sucesso.":`Teste não confirmado: ${r?.error??"falha de entrega"}`);await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha no teste do webhook.")}finally{setBusy(false)}}

 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">SIGDEC · ADMINISTRAÇÃO · v1.45</span><h1>Administração do sistema</h1><p>Usuários, perfis, itens, módulos, integrações e relatórios.</p></div><div className="headerActions"><Link className="primaryButton" href="/administracao/usuarios">Usuários e dados</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {message&&<section className="infoCard">{message}</section>}{secretNotice&&<section className="warningCard"><strong>Segredo exibido uma única vez</strong><p style={{wordBreak:"break-all",fontFamily:"monospace"}}>{secretNotice}</p></section>}
  <section><h2>Módulos ativos</h2><p>O bloqueio é aplicado também na API; desativar um módulo não apaga dados.</p><div className="dataGrid">{features.map(x=><article className={x.enabled?"card":"warningCard"} key={x.code}><h2>{x.label}</h2><p><strong>{x.enabled?"Ativo":"Desativado"}</strong> · {x.code}</p><button type="button" className={x.enabled?"secondaryLink":"primaryButton"} disabled={busy} onClick={()=>void toggleFeature(x)}>{x.enabled?"Desativar":"Ativar"}</button></article>)}</div></section>
  <section style={{marginTop:20}}><h2>Integrações e webhooks</h2><form className="incidentForm compactForm" onSubmit={addIntegration}><label>Nome<input name="name" required/></label><label>Tipo<select name="type"><option value="API">API</option><option value="WEBHOOK">Webhook</option><option value="IMPORT">Importação</option><option value="EXPORT">Exportação</option></select></label><label>Endpoint / URL<input name="url" type="url" placeholder="https://..."/></label><label>Descrição<input name="description"/></label><label>Filtro de eventos (prefixo da ação)<input name="eventPrefix" placeholder="Ex.: incident."/></label><label><input name="includeData" type="checkbox"/> Incluir before/after nos eventos (pode conter dados pessoais)</label><button className="primaryButton" disabled={busy}>Cadastrar integração</button></form><div className="dataGrid" style={{marginTop:12}}>{integrations.length===0?<div className="infoCard">Nenhuma integração cadastrada.</div>:integrations.map(x=><article className={x.active?"card":"warningCard"} key={x.id}><h2>{x.name}</h2><p><strong>{x.integrationType}</strong> · {x.active?"ativa":"inativa"}</p>{x.endpointUrl&&<p>{x.endpointUrl}</p>}{x.integrationType==="WEBHOOK"&&<><p>Assinatura: {x.webhookSecretConfigured?"configurada":"não configurada"} · pendentes {x.pendingDeliveries??0} · falhas {x.failedDeliveries??0}</p><p>Falhas consecutivas: {x.deliveryFailureCount??0}{x.lastDeliveryAt?` · última entrega ${formatDateTimeBR(x.lastDeliveryAt)}`:""}</p><div className="headerActions"><button type="button" className="secondaryLink" disabled={busy} onClick={()=>void rotateSecret(x)}>Rotacionar segredo</button><button type="button" className="secondaryLink" disabled={busy||!x.active||!x.webhookSecretConfigured} onClick={()=>void testWebhook(x)}>Testar webhook</button></div></>}<button type="button" className="secondaryLink" disabled={busy} onClick={()=>void toggleIntegration(x)}>{x.active?"Desativar":"Ativar"}</button></article>)}</div></section>
 </main>;
}
