"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {SIGDEC_VERSION_LABEL} from "../../lib/release";
import {formatDateTimeBR} from "../../lib/datetime";
import {useRealtimeRefresh} from "../../lib/use-realtime-refresh";

const API=process.env.NEXT_PUBLIC_SIGDEC_API_URL??"http://localhost:4000";
type Integration={id:string;name:string;integrationType:"API"|"WEBHOOK"|"IMPORT"|"EXPORT";endpointUrl?:string|null;active:boolean;config?:Record<string,unknown>;webhookSecretConfigured?:boolean;lastDeliveryAt?:string|null;deliveryFailureCount?:number;pendingDeliveries?:number;failedDeliveries?:number};

export default function IntegrationsPage(){
 const[items,setItems]=useState<Integration[]>([]),[message,setMessage]=useState(""),[secretNotice,setSecretNotice]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(path:string,init?:RequestInit)=>{const r=await fetch(API+path,{credentials:"include",cache:"no-store",...init,headers:{"content-type":"application/json",...(init?.headers??{})}});if(r.status===401){location.href="/login";throw new Error("Sessão expirada.")}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message??b.error??"Falha na integração.");return b},[]);
 const load=useCallback(async()=>{try{const b=await request("/api/v1/admin/integrations");setItems(b.items??[])}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar integrações.")}},[request]);
 useEffect(()=>{void load()},[load]);useRealtimeRefresh(()=>{if(!busy)return load()},true,15000);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");setSecretNotice("");const f=new FormData(e.currentTarget);try{const r=await request("/api/v1/admin/integrations",{method:"POST",body:JSON.stringify({name:String(f.get("name")),integrationType:String(f.get("type")),endpointUrl:String(f.get("url")||"")||undefined,active:true,config:{description:String(f.get("description")||""),eventPrefix:String(f.get("eventPrefix")||""),includeData:f.get("includeData")==="on"}})});e.currentTarget.reset();setMessage("Integração cadastrada.");if(r.webhookSecret)setSecretNotice("Segredo do webhook (salve agora): "+r.webhookSecret);await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function toggle(x:Integration){setBusy(true);try{await request("/api/v1/admin/integrations/"+x.id+"/status",{method:"PATCH",body:JSON.stringify({active:!x.active})});await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function rotate(x:Integration){setBusy(true);setSecretNotice("");try{const r=await request("/api/v1/admin/integrations/"+x.id+"/rotate-secret",{method:"POST"});if(r.webhookSecret)setSecretNotice("Novo segredo de "+x.name+" (salve agora): "+r.webhookSecret);setMessage("Segredo rotacionado.");await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha.")}finally{setBusy(false)}}
 async function test(x:Integration){setBusy(true);try{const r=await request("/api/v1/admin/integrations/"+x.id+"/test",{method:"POST"});setMessage(r.success?"Webhook testado com sucesso.":"Teste não confirmado: "+(r.error??"falha de entrega"));await load()}catch(e){setMessage(e instanceof Error?e.message:"Falha no teste.")}finally{setBusy(false)}}
 return <main className="shell moduleShell">
  <header className="listHeader"><div><span className="eyebrow">ADMINISTRAÇÃO · INTEGRAÇÕES · {SIGDEC_VERSION_LABEL}</span><h1>Integrações</h1><p>Ponto único para conexões do SIGDEC com sistemas externos, APIs, webhooks, importações e exportações.</p></div><div className="headerActions"><Link className="secondaryLink" href="/administracao">Administração</Link><Link className="secondaryLink" href="/painel">Painel</Link></div></header>
  {message&&<section className="infoCard">{message}</section>}{secretNotice&&<section className="warningCard"><strong>Segredo exibido uma única vez</strong><p style={{wordBreak:"break-all",fontFamily:"monospace"}}>{secretNotice}</p></section>}
  <section className="dataGrid">
   <article className="card"><span className="eyebrow">TERRITÓRIO</span><h2>GeoPixel</h2><p>Camadas WFS/WMS/GeoJSON, sincronização territorial e inteligência geoespacial.</p><Link className="primaryButton" href="/administracao/geopixel">Configurar GeoPixel</Link></article>
   <article className="card"><span className="eyebrow">PROCESSOS</span><h2>SEI Cidades</h2><p>Web Services, processos vinculados, documentos e operações auditadas.</p><Link className="primaryButton" href="/administracao/sei">Configurar SEI</Link></article>
   <article className="card"><span className="eyebrow">INTEROPERABILIDADE</span><h2>SIDEC</h2><p>A interoperabilidade SIDEC permanece vinculada às ocorrências e à continuidade operacional; suas conexões são governadas por esta área.</p><Link className="secondaryLink" href="/ocorrencias">Abrir ocorrências</Link></article>
  </section>
  <section className="detailSection" style={{marginTop:20}}><h2>Nova integração genérica</h2><form className="incidentForm compactForm" onSubmit={add}><label>Nome<input name="name" required/></label><label>Tipo<select name="type"><option value="API">API</option><option value="WEBHOOK">Webhook</option><option value="IMPORT">Importação</option><option value="EXPORT">Exportação</option></select></label><label>Endpoint / URL<input name="url" type="url" placeholder="https://..."/></label><label>Descrição<input name="description"/></label><label>Filtro de eventos<input name="eventPrefix" placeholder="Ex.: incident."/></label><label><input name="includeData" type="checkbox"/> Incluir dados before/after nos eventos quando necessário e autorizado</label><button className="primaryButton" disabled={busy}>Cadastrar integração</button></form></section>
  <section style={{marginTop:20}}><h2>Integrações cadastradas</h2><div className="dataGrid">{items.length===0?<div className="infoCard">Nenhuma integração genérica cadastrada.</div>:items.map(x=><article className={x.active?"card":"warningCard"} key={x.id}><h2>{x.name}</h2><p><strong>{x.integrationType}</strong> · {x.active?"ativa":"inativa"}</p>{x.endpointUrl&&<p>{x.endpointUrl}</p>}{x.integrationType==="WEBHOOK"&&<><p>Assinatura: {x.webhookSecretConfigured?"configurada":"não configurada"} · pendentes {x.pendingDeliveries??0} · falhas {x.failedDeliveries??0}</p><p>Falhas consecutivas: {x.deliveryFailureCount??0}{x.lastDeliveryAt?" · última entrega "+formatDateTimeBR(x.lastDeliveryAt):""}</p><div className="headerActions"><button type="button" className="secondaryButton" disabled={busy} onClick={()=>void rotate(x)}>Rotacionar segredo</button><button type="button" className="secondaryButton" disabled={busy} onClick={()=>void test(x)}>Testar webhook</button></div></>}<button type="button" className="secondaryButton" disabled={busy} onClick={()=>void toggle(x)}>{x.active?"Desativar":"Ativar"}</button></article>)}</div></section>
 </main>
}
